// NPTEL Introduction to Machine Learning Question Bank
// Module 1 (Week 1): Foundations & Evaluation (Prof. Sudeshna Sarkar, IIT Kharagpur)
// Module 2 (Week 2): Linear Regression & Decision Trees (Prof. Sudeshna Sarkar, IIT Kharagpur)

const WEEK1_QUESTIONS = [
  {
    id: 1,
    question: "According to Mitchell's definition, a program is said to 'learn' if its performance at tasks in T, as measured by P, improves with which of the following?",
    options: [
      "The size of the hypothesis space",
      "Experience E",
      "The number of features",
      "The learning rate"
    ],
    correctAnswer: "Experience E",
    explanation: "Mitchell's classic definition: a program learns from experience E with respect to task T and performance measure P if its performance at T, as measured by P, improves with E."
  },
  {
    id: 2,
    question: "A data scientist has unlabelled sensor readings and wants the model to learn purely from trial-and-error feedback (reward/punishment) while interacting with a live system. Which learning paradigm fits best?",
    options: [
      "Supervised Learning",
      "Unsupervised Learning",
      "Reinforcement Learning",
      "Semi-Supervised Learning"
    ],
    correctAnswer: "Reinforcement Learning",
    explanation: "Reinforcement learning determines actions based on rewards and punishments received from an environment, not from pre-labelled data."
  },
  {
    id: 3,
    question: "In the semi-supervised learning diagram from the slides, what additional data (beyond labeled data) is used to help find a better classification plane?",
    options: [
      "Synthetic labeled data generated by another classifier",
      "Unlabeled data from the same distribution",
      "Data from a completely different domain",
      "Only the test set"
    ],
    correctAnswer: "Unlabeled data from the same distribution",
    explanation: "Semi-supervised learning uses both labeled and unlabeled data (from the same distribution) to improve the learned decision boundary compared to using labeled data alone."
  },
  {
    id: 4,
    question: "In the Reinforcement Learning diagram (Agent–Environment loop), which two signals does the Environment send back to the Agent after it takes an action a_t?",
    options: [
      "State s_t+1 and Reward r_t+1",
      "Only the reward",
      "A new action and a label",
      "The target function and a feature vector"
    ],
    correctAnswer: "State s_t+1 and Reward r_t+1",
    explanation: "The environment responds to an action with the next state (s_t+1) and a reward (r_t+1), which the agent uses to update its policy."
  },
  {
    id: 5,
    question: "Which of the following is the best example of an Unsupervised Learning task?",
    options: [
      "Predicting house prices from area and location",
      "Grouping news articles into topics without any predefined categories",
      "Classifying emails as spam or not spam using labeled training data",
      "Training a robot arm using reward signals"
    ],
    correctAnswer: "Grouping news articles into topics without any predefined categories",
    explanation: "Grouping/clustering data without pre-existing labels is the defining example of unsupervised learning."
  },
  {
    id: 6,
    question: "Which statement correctly distinguishes Classification from Regression?",
    options: [
      "Classification predicts continuous values; Regression predicts discrete labels",
      "Classification predicts a discrete/categorical target Y; Regression predicts a continuous target Y",
      "Both always predict continuous values but classification uses more features",
      "Regression cannot use numerical features"
    ],
    correctAnswer: "Classification predicts a discrete/categorical target Y; Regression predicts a continuous target Y",
    explanation: "As stated in the slides: classification is used when Y is discrete, and regression is used when Y is continuous."
  },
  {
    id: 7,
    question: "A dataset field records temperature as 'Low', 'Medium', 'High'. What type of feature is this?",
    options: [
      "Categorical (nominal)",
      "Ordinal",
      "Integer-valued",
      "Real-valued"
    ],
    correctAnswer: "Ordinal",
    explanation: "'Low/Medium/High' has a natural order, so it is an ordinal feature (like 'large/medium/small' in the slides), not a plain categorical (nominal) one."
  },
  {
    id: 8,
    question: "In the terminology used in the slides, what is a 'Feature Vector'?",
    options: [
      "A set of all possible labels",
      "An n-dimensional vector of features that represents an object",
      "The function that maps features to labels",
      "A single scalar performance score"
    ],
    correctAnswer: "An n-dimensional vector of features that represents an object",
    explanation: "Feature vector: n-dimensional vector of numerical features that represent some object, e.g. d = <x1, x2, ..., xn>."
  },
  {
    id: 9,
    question: "What is the 'Instance Space X' as defined in the slides?",
    options: [
      "The set of all training examples only",
      "The set of all possible objects describable by the features",
      "The set of all hypotheses a learner can produce",
      "The set of all class labels"
    ],
    correctAnswer: "The set of all possible objects describable by the features",
    explanation: "Instance Space X is defined as the set of all possible objects describable by the features — much larger than just the training set."
  },
  {
    id: 10,
    question: "An 'Example (x, y)' as used in the slides refers to:",
    options: [
      "Two different instances being compared",
      "An instance x together with its label y = f(x)",
      "A hypothesis paired with its accuracy",
      "A feature paired with its data type"
    ],
    correctAnswer: "An instance x together with its label y = f(x)",
    explanation: "An example is an instance x with its label y=f(x) — the (input, output) pair used for training/testing."
  },
  {
    id: 11,
    question: "A learner restricts itself to only using decision rules of the form 'IF condition THEN class', ignoring all other possible functions. This is an example of which kind of inductive bias?",
    options: [
      "Preference bias",
      "Restriction bias",
      "Variance bias",
      "Sample bias"
    ],
    correctAnswer: "Restriction bias",
    explanation: "Restriction bias limits the hypothesis space itself (e.g., only considering rule-based hypotheses), as opposed to preference bias which orders hypotheses within an unrestricted space."
  },
  {
    id: 12,
    question: "Among two hypotheses that are both perfectly consistent with the training data, a learner always picks the one that is simpler / shorter to describe. This illustrates which principle?",
    options: [
      "Maximum margin principle",
      "Occam's Razor",
      "Cross-validation",
      "The bias-variance decomposition"
    ],
    correctAnswer: "Occam's Razor",
    explanation: "Occam's Razor: the simplest hypothesis consistent with the data is preferred — a classic example of inductive (preference) bias."
  },
  {
    id: 13,
    question: "If a dataset has 5 independent boolean input features, how many unique Boolean functions can theoretically be defined over this feature space?",
    options: [
      "2^5 = 32",
      "2^10 = 1,024",
      "2^32 = 4,294,967,296",
      "2^16 = 65,536"
    ],
    correctAnswer: "2^32 = 4,294,967,296",
    explanation: "Number of Boolean functions over N boolean features = 2^(2^N). For N=5, this is 2^(2^5) = 2^32 = 4,294,967,296."
  },
  {
    id: 14,
    question: "If a dataset has only 2 independent boolean input features, how many unique Boolean functions can theoretically be defined over this feature space?",
    options: [
      "4",
      "8",
      "16",
      "32"
    ],
    correctAnswer: "16",
    explanation: "Formula: 2^(2^N). With N=2, this gives 2^(2^2) = 2^4 = 16 possible Boolean functions."
  },
  {
    id: 15,
    question: "Which of the following best defines the Hypothesis Space H in supervised learning?",
    options: [
      "The set of all training examples available",
      "The set of all functions the learning algorithm is allowed to consider while approximating the target function f",
      "The subset of features selected after feature selection",
      "The confusion matrix computed on the test set"
    ],
    correctAnswer: "The set of all functions the learning algorithm is allowed to consider while approximating the target function f",
    explanation: "Hypothesis Space H is the set of functions we allow for approximating f; the learner searches within this space (Input: training set S ⊆ X, Output: a hypothesis h ∈ H)."
  },
  {
    id: 16,
    question: "Which is an example of a 'preference bias' rather than a 'restriction bias'?",
    options: [
      "Only allowing linear decision boundaries",
      "Only allowing decision trees of depth ≤ 3",
      "Among all consistent decision trees, preferring the shortest one (Occam's Razor)",
      "Only allowing conjunctive Boolean concepts"
    ],
    correctAnswer: "Among all consistent decision trees, preferring the shortest one (Occam's Razor)",
    explanation: "Restriction bias limits which hypotheses are even considered (e.g., only linear, only shallow trees, only conjunctions). Preference bias instead ranks/orders hypotheses within a space that isn't restricted — Occam's Razor is the classic preference bias example."
  },
  {
    id: 17,
    question: "SVM's approach of choosing the decision boundary that maximizes the margin between two classes is an example of which type of inductive bias?",
    options: [
      "Restriction bias",
      "Maximum margin bias (a preference bias)",
      "Minimum description length bias",
      "No bias at all"
    ],
    correctAnswer: "Maximum margin bias (a preference bias)",
    explanation: "Maximum margin is explicitly listed as a type of inductive bias: when drawing a boundary between two classes, attempt to maximize the width of the boundary (used in SVMs)."
  },
  {
    id: 18,
    question: "The 'Inductive Learning Hypothesis' states that:",
    options: [
      "Any hypothesis that fits the training data will always fit unseen data perfectly",
      "A hypothesis that approximates the target function well over a sufficiently large training set will also approximate it well over other unobserved examples",
      "Inductive learning can only work with linear functions",
      "More features always lead to better generalization"
    ],
    correctAnswer: "A hypothesis that approximates the target function well over a sufficiently large training set will also approximate it well over other unobserved examples",
    explanation: "This is the direct definition given in the slides of the Inductive Learning Hypothesis."
  },
  {
    id: 19,
    question: "A binary classifier is evaluated on 400 samples: 250 actual positives, 150 actual negatives. It predicts 220 positives total, of which 200 are correctly predicted positive. What is the Recall of this classifier?",
    options: [
      "80% (200/250)",
      "90.9% (200/220)",
      "50% (200/400)",
      "75% (150/200)"
    ],
    correctAnswer: "80% (200/250)",
    explanation: "Recall = TP / (Actual Positives) = 200 / 250 = 0.80 = 80%."
  },
  {
    id: 20,
    question: "Using the same classifier as above (220 predicted positive, 200 of which are truly positive), what is the Precision?",
    options: [
      "80.0%",
      "≈90.9% (200/220)",
      "75.5%",
      "85.0%"
    ],
    correctAnswer: "≈90.9% (200/220)",
    explanation: "Precision = TP / (Predicted Positives) = 200 / 220 ≈ 0.909 = 90.9%."
  },
  {
    id: 21,
    question: "A model has Precision = 0.8 and Recall = 0.5. What is its F1-Score (to 2 decimal places)?",
    options: [
      "0.65",
      "0.62",
      "0.40",
      "0.70"
    ],
    correctAnswer: "0.62",
    explanation: "F1 = 2 * (P * R) / (P + R) = 2 * (0.8 * 0.5) / (0.8 + 0.5) = 0.8 / 1.3 ≈ 0.6154, rounded to 0.62."
  },
  {
    id: 22,
    question: "In a confusion matrix, if TP=50, FP=10, FN=20, TN=120, what is the Accuracy?",
    options: [
      "80%",
      "85% ((50+120)/200)",
      "75%",
      "90%"
    ],
    correctAnswer: "85% ((50+120)/200)",
    explanation: "Accuracy = (TP + TN) / (TP + TN + FP + FN) = (50 + 120) / 200 = 170 / 200 = 0.85 = 85%."
  },
  {
    id: 23,
    question: "In a confusion matrix, if TP=50, FP=10, FN=20, TN=120, what is the False Positive Rate (FP Rate)?",
    options: [
      "10/130 ≈ 7.7%",
      "10/60 ≈ 16.7%",
      "10/200 = 5.0%",
      "20/140 ≈ 14.3%"
    ],
    correctAnswer: "10/130 ≈ 7.7%",
    explanation: "FP Rate = FP / Actual Negatives = FP / (FP + TN) = 10 / (10 + 120) = 10 / 130 ≈ 0.0769 = 7.7%."
  },
  {
    id: 24,
    question: "Which metric answers the question: 'Of all instances the model predicted as positive, how many were actually positive?'",
    options: [
      "Recall",
      "Precision",
      "Accuracy",
      "FP Rate"
    ],
    correctAnswer: "Precision",
    explanation: "Precision = TP / (TP + FP) — the fraction of predicted positives that are truly positive."
  },
  {
    id: 25,
    question: "Which metric answers the question: 'Of all the actual positive instances, how many did the model correctly identify?'",
    options: [
      "Precision",
      "Recall (also called TP rate/Sensitivity)",
      "Specificity",
      "F1-Score only"
    ],
    correctAnswer: "Recall (also called TP rate/Sensitivity)",
    explanation: "Recall = TP / P (actual positives) — this is also called the True Positive Rate or Sensitivity."
  },
  {
    id: 26,
    question: "Why is Accuracy often a misleading metric on highly imbalanced datasets (e.g., 990 negatives, 10 positives)?",
    options: [
      "Accuracy cannot be computed for imbalanced data at all",
      "A model that always predicts 'negative' would still get 99% accuracy while catching zero positives",
      "Accuracy always equals Precision in imbalanced data",
      "Imbalanced datasets have no negatives"
    ],
    correctAnswer: "A model that always predicts 'negative' would still get 99% accuracy while catching zero positives",
    explanation: "With heavy class imbalance, a trivial always-predict-majority-class model scores very high accuracy despite being useless for detecting the minority (often more important) class — that's why Precision/Recall/F1 are preferred there."
  },
  {
    id: 27,
    question: "Which of the following correctly characterizes an Underfit model?",
    options: [
      "Low bias, high variance",
      "High bias, low variance — the model is too simple to capture the pattern",
      "High training accuracy, low test accuracy",
      "Zero error on both training and test data"
    ],
    correctAnswer: "High bias, low variance — the model is too simple to capture the pattern",
    explanation: "Underfitting occurs when the model is too simple: it shows high bias and low variance, with high error on both training and test sets."
  },
  {
    id: 28,
    question: "A decision tree is grown until every leaf is pure (100% training accuracy) but performs poorly on unseen data. What does this indicate about its bias and variance?",
    options: [
      "Low bias, high variance (overfitting)",
      "High bias, low variance (underfitting)",
      "Both bias and variance are zero",
      "This indicates a data leakage problem, not overfitting"
    ],
    correctAnswer: "Low bias, high variance (overfitting)",
    explanation: "A model that perfectly fits training data but generalizes poorly is overfitting: it has low bias (fits training data well) but high variance (very sensitive to the specific training set)."
  },
  {
    id: 29,
    question: "What does the 'Variance' component of generalization error measure?",
    options: [
      "How much the average model over all training sets differs from the true model",
      "How much models trained on different training sets differ from each other",
      "The number of features used by the model",
      "The total training time of the model"
    ],
    correctAnswer: "How much models trained on different training sets differ from each other",
    explanation: "Variance measures how much models estimated from different training sets differ from each other — high variance means the model is highly sensitive to the particular training sample."
  },
  {
    id: 30,
    question: "Model A has low bias and high variance. Model B has high bias and low variance. Which statement is most accurate?",
    options: [
      "Model A likely overfits the training data; Model B likely underfits it",
      "Model A always has lower test error than Model B",
      "Both models have identical generalization error",
      "Model B is guaranteed to memorize the training set"
    ],
    correctAnswer: "Model A likely overfits the training data; Model B likely underfits it",
    explanation: "Low bias/high variance is the classic signature of overfitting, while high bias/low variance is the classic signature of underfitting."
  },
  {
    id: 31,
    question: "Which of the following is NOT listed among the causes of error in machine learning according to the slides?",
    options: [
      "Limited representation (representation bias)",
      "Limited search (search bias)",
      "Limited data (variance)",
      "Excessive computational power of the hardware"
    ],
    correctAnswer: "Excessive computational power of the hardware",
    explanation: "The slides list limited representation, limited search, limited data (variance), and limited/noisy features as causes of learning error — hardware power is not one of them."
  },
  {
    id: 32,
    question: "Which combination of statements about overfitting is correct?\nI. Overfitting leads to poor generalization on unseen data.\nII. Overfitting usually results in low training error.\nIII. Overfitting always improves test accuracy.",
    options: [
      "I only",
      "I and II only",
      "II and III only",
      "I, II and III"
    ],
    correctAnswer: "I and II only",
    explanation: "Overfitting causes poor generalization (I, true) and typically very low training error since the model fits the training data closely (II, true), but it does NOT improve test accuracy — in fact it usually hurts it (III, false)."
  },
  {
    id: 33,
    question: "Why does a single train/test split sometimes give an unreliable estimate of a model's true performance?",
    options: [
      "Because train/test splits are illegal in machine learning",
      "Because the small test set can have high variance in its estimate of error",
      "Because train/test splits always overestimate accuracy",
      "Because test sets cannot contain labels"
    ],
    correctAnswer: "Because the small test set can have high variance in its estimate of error",
    explanation: "With a single, possibly small, test set, the estimate of error has high variance — different random splits can give quite different error estimates."
  },
  {
    id: 34,
    question: "In 10-fold cross-validation, what fraction of the data is used as the test/validation set in each round?",
    options: [
      "1/2",
      "1/5",
      "1/10",
      "All of the data"
    ],
    correctAnswer: "1/10",
    explanation: "In k-fold cross-validation, 1/k of the data is held out as the test set each round; for k=10, that is 1/10 of the data."
  },
  {
    id: 35,
    question: "What is the main advantage of k-fold cross-validation over a single fixed validation set?",
    options: [
      "It uses all the available data for both training and testing across different rounds, reducing wasted data",
      "It requires no computation at all",
      "It removes the need for a test set entirely",
      "It guarantees zero overfitting"
    ],
    correctAnswer: "It uses all the available data for both training and testing across different rounds, reducing wasted data",
    explanation: "A single validation split 'fails to use all the available data' (as the slides note); k-fold cross-validation rotates which portion is held out so every example is eventually used for both training and testing, giving a more robust estimate."
  },
  {
    id: 36,
    question: "The final reported score in k-fold cross-validation is typically computed as:",
    options: [
      "The score on the very last fold only",
      "The maximum score across all folds",
      "The average of the test-set scores across all k rounds",
      "The score on the full, unsplit dataset"
    ],
    correctAnswer: "The average of the test-set scores across all k rounds",
    explanation: "As shown in the slides: Final Accuracy = Average(Round 1, Round 2, ..., Round k)."
  },
  {
    id: 37,
    question: "What is the key difference between 'sample error' and 'true error' of a hypothesis?",
    options: [
      "Sample error is computed on data sample S; true error is the probability of misclassifying an instance drawn from the whole distribution D",
      "They are always numerically identical",
      "True error can only be computed for regression, sample error only for classification",
      "Sample error requires infinite data, true error requires only one example"
    ],
    correctAnswer: "Sample error is computed on data sample S; true error is the probability of misclassifying an instance drawn from the whole distribution D",
    explanation: "Sample error is measured on a finite sample S; true error (error_D) is the probability of misclassification over the entire underlying distribution D, which sample error only estimates."
  },
  {
    id: 38,
    question: "Why do we care about performance on the underlying distribution D rather than just on the training data?",
    options: [
      "Because training data is always corrupted",
      "Because the goal of learning is to generalize well to new, unseen data drawn from D, not just memorize training data",
      "Because training data has no labels",
      "Because the distribution D is always identical to the training set"
    ],
    correctAnswer: "Because the goal of learning is to generalize well to new, unseen data drawn from D, not just memorize training data",
    explanation: "As emphasized in the slides: 'we care about performance on the distribution, not the training data' — generalization to unseen data is the real objective."
  },
  {
    id: 39,
    question: "According to the machine learning history timeline in the slides, which decade is Rosenblatt's Perceptron and Minsky & Papert's proof of its limitations associated with?",
    options: [
      "1950s",
      "1960s",
      "1970s",
      "1980s"
    ],
    correctAnswer: "1960s",
    explanation: "The 1960s slide lists: Neural network — Rosenblatt's perceptron; Minsky & Papert prove limitations of Perceptron."
  },
  {
    id: 40,
    question: "Which of these milestones is correctly matched to its year according to the slides?",
    options: [
      "1997 — Deep Blue beats Garry Kasparov",
      "1994 — Watson wins Jeopardy",
      "2009 — Deep Blue beats Garry Kasparov",
      "2011 — Google builds a self-driving car"
    ],
    correctAnswer: "1997 — Deep Blue beats Garry Kasparov",
    explanation: "The slides list: 1994 — Self-driving car road test; 1997 — Deep Blue beats Garry Kasparov; 2009 — Google builds self-driving car; 2011 — Watson wins Jeopardy."
  },
  {
    id: 41,
    question: "Which of the following is NOT listed in the slides as a reason for ML's recent surge in popularity?",
    options: [
      "New software/algorithms (e.g., deep learning)",
      "New hardware (GPUs)",
      "Cloud enabled computing and availability of Big Data",
      "Reduction in the number of available features"
    ],
    correctAnswer: "Reduction in the number of available features",
    explanation: "The slides list new software/algorithms, new hardware (GPUs), cloud enablement, and availability of Big Data as reasons for ML's popularity — not a reduction in features."
  },
  {
    id: 42,
    question: "In the 'Algorithmic solution vs Machine learning solution' diagram, what are the two inputs to the computer in the Machine Learning solution (as opposed to the Algorithmic solution)?",
    options: [
      "Data and Program",
      "Data and Output",
      "Program and Output",
      "Only Data"
    ],
    correctAnswer: "Data and Output",
    explanation: "In the ML solution, the computer takes Data and Output (desired results) as input and produces the Program (model) as output — reversing the classical algorithmic approach of Data+Program -> Output."
  },
  {
    id: 43,
    question: "According to the 'Design a Learner' framework in the slides, what is the correct order of steps?",
    options: [
      "Choose learning algorithm -> Choose training experience -> Choose target function -> Choose representation",
      "Choose the training experience -> Choose the target function -> Choose how to represent the target function -> Choose a learning algorithm to infer it",
      "Choose representation -> Choose training experience -> Choose learning algorithm -> Choose target function",
      "There is no defined order; all steps happen simultaneously"
    ],
    correctAnswer: "Choose the training experience -> Choose the target function -> Choose how to represent the target function -> Choose a learning algorithm to infer it",
    explanation: "The slides list these four steps in this exact order for designing a learner."
  },
  {
    id: 44,
    question: "In the Classification Learning framework (Task T, Performance metric P, Experience E), what does 'Experience E' typically consist of?",
    options: [
      "A set of unlabeled instances only",
      "A set of labeled examples (x, y) sampled from a fixed distribution D",
      "The set of all possible hypotheses",
      "The accuracy score of the final model"
    ],
    correctAnswer: "A set of labeled examples (x, y) sampled from a fixed distribution D",
    explanation: "Experience E is defined as a set of labeled examples (x,y) where y is the true label for x, ideally sampled from a fixed distribution D."
  },
  {
    id: 45,
    question: "For the task of 'finding entity names in text', what would typically serve as the Instance and Label according to the classification learning table in the slides?",
    options: [
      "Instance: a whole document; Label: the document's topic",
      "Instance: a word in context (e.g., capitalization, nearby words); Label: {first, later, outside}",
      "Instance: an image; Label: {0,1}",
      "Instance: lab readings; Label: risk of heart disease"
    ],
    correctAnswer: "Instance: a word in context (e.g., capitalization, nearby words); Label: {first, later, outside}",
    explanation: "The slides' example table lists: Task = finding entity names in text; Instance = a word in context (capitalized, nearby words, ...); Labels = {first, later, outside}."
  },
  {
    id: 46,
    question: "Why is 'Diagnosing a disease' a good example of a task requiring historical medical records as Data (per the slides)?",
    options: [
      "Because the output labels (disease/no disease) can only be obtained by waiting and observing outcomes over time, which historical records capture",
      "Because medical records never contain any useful features",
      "Because diagnosis tasks never need any training data",
      "Because this is purely an unsupervised learning task"
    ],
    correctAnswer: "Because the output labels (disease/no disease) can only be obtained by waiting and observing outcomes over time, which historical records capture",
    explanation: "The slides note that for medical diagnosis, data comes from historical medical records, and learning involves determining which future patients will respond best to which treatments — i.e., learning from past labeled outcomes."
  }
];

// Week 2 Question Bank: Linear Regression & Decision Trees (45 Questions)
// Sourced directly from Module 2 Practice Questions with Answers (Prof. Sudeshna Sarkar, IIT Kharagpur)
const WEEK2_QUESTIONS = [
  // Section A: Linear Regression (Q1–Q21)
  {
    id: 1,
    question: "In regression, the predicted output variable is:",
    options: [
      "Discrete/categorical",
      "Continuous",
      "Always binary (0/1)",
      "Always a time-series"
    ],
    correctAnswer: "Continuous",
    explanation: "Regression problems predict a continuous-valued output, unlike classification which predicts discrete class labels."
  },
  {
    id: 2,
    question: "Which loss function is used in the polynomial curve-fitting example to measure how well a curve fits the data?",
    options: [
      "Absolute error",
      "Squared error in the prediction of y(x) from x",
      "Hinge loss",
      "Cross-entropy loss"
    ],
    correctAnswer: "Squared error in the prediction of y(x) from x",
    explanation: "The slides state a loss function that measures the squared error in the prediction of y(x) from x."
  },
  {
    id: 3,
    question: "In (regularized) linear regression, overfitting is typically characterized by:",
    options: [
      "Very small (near-zero) weights",
      "Large weights, making the model overly sensitive to the training data",
      "Weights that are always exactly zero",
      "Weights that are always positive"
    ],
    correctAnswer: "Large weights, making the model overly sensitive to the training data",
    explanation: "The slides note that overfitting in a linear regression model is characterized by large weights — regularization penalizes large weights to control this."
  },
  {
    id: 4,
    question: "In the simple linear regression equation E(y) = b0 + b1x, what does b0 (the intercept) represent?",
    options: [
      "The slope of the regression line",
      "The predicted value of y when x = 0",
      "The random error term",
      "The correlation coefficient between x and y"
    ],
    correctAnswer: "The predicted value of y when x = 0",
    explanation: "b0 represents the y-intercept, which is the predicted value of y when the predictor variable x equals 0."
  },
  {
    id: 5,
    question: "In the same equation E(y) = b0 + b1x, what does b1 (the slope) represent?",
    options: [
      "The intercept of the line",
      "The change in y for a one-unit change in x",
      "The residual error",
      "The sample size"
    ],
    correctAnswer: "The change in y for a one-unit change in x",
    explanation: "b1 represents the slope of the line, which indicates the change in y for a one-unit increase in x."
  },
  {
    id: 6,
    question: "In the regression model Y = β0 + β1x1 + ε, which term denotes the random error associated with each observation?",
    options: [
      "β0",
      "β1",
      "x1",
      "ε"
    ],
    correctAnswer: "ε",
    explanation: "ε denotes the random unobserved error term associated with each observation."
  },
  {
    id: 7,
    question: "Given 5 data points where X = house size (in 100s of sq. ft.) and Y = price (in $1000s):\nX: 1, 2, 3, 4, 5 | Y: 2, 4, 5, 4, 5\nUsing b1 = (n·Σxy − Σx·Σy) / (n·Σx² − (Σx)²), find the slope b1 (round to 2 decimals).",
    options: [
      "0.60",
      "0.45",
      "1.20",
      "0.80"
    ],
    correctAnswer: "0.60",
    explanation: "n = 5, Σx = 1+2+3+4+5 = 15, Σy = 2+4+5+4+5 = 20, Σxy = 2+8+15+16+25 = 66, Σx² = 1+4+9+16+25 = 55. b1 = (5×66 − 15×20) / (5×55 − 15²) = (330 − 300) / (275 − 225) = 30 / 50 = 0.60."
  },
  {
    id: 8,
    question: "Using the same data as Q7 and b0 = (Σy − b1·Σx) / n, find the intercept b0 (round to 2 decimals).",
    options: [
      "2.20",
      "1.80",
      "3.10",
      "0.95"
    ],
    correctAnswer: "2.20",
    explanation: "From Q7: Σy = 20, Σx = 15, b1 = 0.60, n = 5. b0 = (20 − 0.60×15) / 5 = (20 − 9) / 5 = 11 / 5 = 2.20. The fitted regression line is Y = 2.20 + 0.60X."
  },
  {
    id: 9,
    question: "In multiple linear regression Yi = b0 + b1X1 + b2X2 + ... + bpXp + e, what does b0 represent?",
    options: [
      "The slope associated with X1",
      "The average value of Y when all the X's are zero (the intercept)",
      "The variance of Y",
      "The total number of predictors p"
    ],
    correctAnswer: "The average value of Y when all the X's are zero (the intercept)",
    explanation: "b0 is the intercept parameter, representing the expected value of Y when all predictor variables X1 through Xp equal zero."
  },
  {
    id: 10,
    question: "Which of the following are standard assumptions made about the random error εi in a regression model?\nI. E(εi) = 0 for i = 1, 2, ..., n\nII. The errors are independent of each other\nIII. The errors are normally distributed with mean 0 and a fixed standard deviation σ\nIV. The errors must always be positive",
    options: [
      "I, II, and III only",
      "I and II only",
      "II and III only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and III only",
    explanation: "The slides list E(εi)=0, independence, and normal distribution N(0,σ) as standard error assumptions. Errors can be positive or negative — assumption IV is false."
  },
  {
    id: 11,
    question: "The least-squares regression line is defined as the line that:",
    options: [
      "Passes through the maximum possible number of data points",
      "Minimizes the sum of the squared vertical (y) distances between the data points and the line",
      "Maximizes the correlation coefficient between x and y",
      "Minimizes the number of features used in the model"
    ],
    correctAnswer: "Minimizes the sum of the squared vertical (y) distances between the data points and the line",
    explanation: "The least-squares method finds the line that minimizes the sum of squared vertical distances (residuals) between observed points and the regression line."
  },
  {
    id: 12,
    question: "The method of least squares chooses b0 and b1 to minimize which quantity, given observations (xi, yi)?",
    options: [
      "Σ|yi − (b0 + b1xi)|",
      "Σ[yi − (b0 + b1xi)]²",
      "Σ(yi − ȳ)",
      "Σ(xi − x̄)²"
    ],
    correctAnswer: "Σ[yi − (b0 + b1xi)]²",
    explanation: "Least squares explicitly minimizes the sum of squared errors (SSE): Σ[yi − (b0 + b1xi)]²."
  },
  {
    id: 13,
    question: "To find the coefficients that minimize the Sum of Squared Errors (SSE) objective function, the standard approach is to:",
    options: [
      "Take partial derivatives of SSE with respect to each coefficient, set them to zero, and solve",
      "Randomly search all possible coefficient values until one works",
      "Use only the maximum values of x and y in the dataset",
      "Always fix b0 = 0 and solve only for b1"
    ],
    correctAnswer: "Take partial derivatives of SSE with respect to each coefficient, set them to zero, and solve",
    explanation: "Setting partial derivatives of SSE with respect to each parameter to zero produces the normal equations, whose solution gives the optimal regression coefficients."
  },
  {
    id: 14,
    question: "Besides the closed-form (matrix inversion) solution, which iterative technique is mentioned for finding the weights in multiple linear regression?",
    options: [
      "K-means clustering",
      "Delta rule, also called the LMS (Least Mean Squares) method",
      "The Apriori algorithm",
      "ID3 decision tree induction"
    ],
    correctAnswer: "Delta rule, also called the LMS (Least Mean Squares) method",
    explanation: "The Delta rule (LMS or Widrow-Hoff learning rule) is an iterative gradient descent technique for finding weights in linear regression."
  },
  {
    id: 15,
    question: "Given hypothesis h(x) = Σβi·xi and cost function J(θ) = (1/2)Σ(h(x(i)) − y(i))², minimizing J(θ) achieves what?",
    options: [
      "Maximizes the count of correctly classified training examples",
      "Finds parameters θ that make predictions h(x) as close as possible to the actual targets y over the training examples",
      "Guarantees zero model bias",
      "Guarantees the smallest possible test error"
    ],
    correctAnswer: "Finds parameters θ that make predictions h(x) as close as possible to the actual targets y over the training examples",
    explanation: "Minimizing J(θ) finds weights θ such that the model predictions h(x) are as close as possible to the true labels y on the training instances."
  },
  {
    id: 16,
    question: "In the gradient descent update rule βj = βj − α·∂J(θ)/∂βj, what does α represent?",
    options: [
      "The number of training iterations",
      "The learning rate (step size)",
      "The number of training examples m",
      "The bias term of the model"
    ],
    correctAnswer: "The learning rate (step size)",
    explanation: "α represents the learning rate (step size), controlling how large a step is taken along the negative gradient direction."
  },
  {
    id: 17,
    question: "Why does gradient descent on the LMS/SSE cost function for linear regression always converge to the global minimum?",
    options: [
      "Because J(θ) is a convex quadratic function with a single global minimum",
      "Because J(θ) is always non-convex, giving many equally good minima",
      "Because the learning rate is always set to exactly 1",
      "Because there is always only one training example"
    ],
    correctAnswer: "Because J(θ) is a convex quadratic function with a single global minimum",
    explanation: "The LMS/SSE cost function is a convex quadratic bowl with only one global minimum, so gradient descent does not get trapped in suboptimal local minima."
  },
  {
    id: 18,
    question: "For a single training example (x, y), what is the LMS parameter update rule?",
    options: [
      "βj = βj − α(y − h(x))xj",
      "βj = βj + α(y − h(x))xj",
      "βj = βj × α(h(x) − y)",
      "βj = α / (y − h(x))"
    ],
    correctAnswer: "βj = βj + α(y − h(x))xj",
    explanation: "The Widrow-Hoff / LMS rule increases βj when the prediction underestimates y: βj = βj + α(y − h(x))xj."
  },
  {
    id: 19,
    question: "What is the key difference between Batch Gradient Descent and Stochastic Gradient Descent (SGD)?",
    options: [
      "Batch GD updates parameters using the entire training set at each step; SGD updates using one training example at a time",
      "Batch GD updates parameters using one training example at a time; SGD uses the entire training set at once",
      "There is no real difference between the two",
      "SGD always converges to a lower final error than Batch GD"
    ],
    correctAnswer: "Batch GD updates parameters using the entire training set at each step; SGD updates using one training example at a time",
    explanation: "Batch GD sums gradients over the entire training set before taking a step, while SGD updates parameters immediately for each individual training example."
  },
  {
    id: 20,
    question: "According to the slides, what problem arises when the Delta rule (which minimizes regression SSE) is applied directly to a classification task?",
    options: [
      "It always produces perfect classification boundaries",
      "It can lead to misclassifications even when the data is linearly separable, since it minimizes regression error rather than maximizing classification accuracy",
      "It only works when there are more than two classes",
      "It guarantees zero training error in every case"
    ],
    correctAnswer: "It can lead to misclassifications even when the data is linearly separable, since it minimizes regression error rather than maximizing classification accuracy",
    explanation: "The Delta rule minimizes squared error, so examples far from the hyperplane produce large penalties even when correctly classified, shifting the decision boundary and causing misclassifications."
  },
  {
    id: 21,
    question: "Fitting a sigmoid/logistic curve (instead of a straight line) to do classification, as shown in the slides, is basically what method?",
    options: [
      "Linear regression",
      "Logistic regression",
      "K-means clustering",
      "Principal Component Analysis"
    ],
    correctAnswer: "Logistic regression",
    explanation: "Logistic regression fits a sigmoid/logistic curve g(z) = 1/(1+e^-z) to constrain predictions between 0 and 1 for classification."
  },

  // Section B: Decision Trees — Basics & ID3 (Q22–Q31)
  {
    id: 22,
    question: "A decision tree classifier is a tree structure made up of which two main types of nodes?",
    options: [
      "Root node and branch node",
      "Decision node and leaf node",
      "Parent node and child node",
      "Input node and output node"
    ],
    correctAnswer: "Decision node and leaf node",
    explanation: "A decision tree consists of internal decision nodes (testing an attribute) and terminal leaf nodes (assigning a class label)."
  },
  {
    id: 23,
    question: "In a decision tree, what does a leaf node represent?",
    options: [
      "A test or choice on some attribute",
      "The classification (or output value) assigned to an example",
      "The root of the tree",
      "A randomly chosen split point"
    ],
    correctAnswer: "The classification (or output value) assigned to an example",
    explanation: "A leaf node specifies the final classification or prediction assigned to instances that traverse down to that node."
  },
  {
    id: 24,
    question: "When choosing which decision tree to generate from training data, a common inductive bias (related to Occam's Razor) is to prefer:",
    options: [
      "The largest, most detailed tree possible",
      "The smallest tree that is consistent with the data",
      "A tree using the maximum possible number of leaf nodes",
      "A tree that always uses every available attribute"
    ],
    correctAnswer: "The smallest tree that is consistent with the data",
    explanation: "Occam's Razor argues a short hypothesis consistent with the data is less likely to be a statistical fluke than a long, convoluted one."
  },
  {
    id: 25,
    question: "A decision tree can be interpreted as representing which logical structure over the attributes?",
    options: [
      "A single large conjunction of all attribute tests",
      "A disjunction of conjunctions — each root-to-leaf path is a conjunction of tests, and the tree is the disjunction (OR) of all such paths leading to the positive class",
      "A single negation of all attribute tests",
      "A linear combination (weighted sum) of the attribute values"
    ],
    correctAnswer: "A disjunction of conjunctions — each root-to-leaf path is a conjunction of tests, and the tree is the disjunction (OR) of all such paths leading to the positive class",
    explanation: "Each root-to-leaf path is a conjunction (AND) of attribute constraints, and the overall tree represents the disjunction (OR) of all paths ending at a target class."
  },
  {
    id: 26,
    question: "In the ID3 top-down induction algorithm, at each step the algorithm:",
    options: [
      "Randomly selects any attribute to split on",
      "Chooses the 'best' decision attribute for the node, assigns it, and creates a new descendant branch for each value of that attribute",
      "Always splits on the attribute that has the greatest number of possible values",
      "Stops only after every attribute has been used, regardless of node purity"
    ],
    correctAnswer: "Chooses the 'best' decision attribute for the node, assigns it, and creates a new descendant branch for each value of that attribute",
    explanation: "ID3 selects the attribute that maximizes information gain, creates a node for it, and branches out for each possible value of that attribute."
  },
  {
    id: 27,
    question: "According to the slides, under which condition(s) should ID3 stop growing a branch of the tree?\nI. There are no more input features left to split on\nII. All training examples at the node are classified the same (already pure)\nIII. There are too few examples remaining to make an informative split\nIV. Only once every single attribute in the dataset has been used, irrespective of purity",
    options: [
      "I, II, and III",
      "I and II only",
      "II and III only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and III",
    explanation: "The slides list three stopping criteria: when all examples have the same label (pure), when no features remain, or when too few examples remain. It does not blindly continue until all attributes are exhausted."
  },
  {
    id: 28,
    question: "What is the principled criterion used by ID3 to decide which attribute is 'best' to test at each node?",
    options: [
      "Euclidean distance between examples",
      "Information gain (based on reduction in entropy)",
      "Alphabetical order of the attribute names",
      "The number of missing values for the attribute"
    ],
    correctAnswer: "Information gain (based on reduction in entropy)",
    explanation: "ID3 measures the effectiveness of an attribute using Information Gain — the expected reduction in entropy resulting from splitting on that attribute."
  },
  {
    id: 29,
    question: "Entropy of a sample S, in terms of the proportion of positive (p+) and negative (p−) examples, is defined as:",
    options: [
      "Entropy(S) = p+ · p−",
      "Entropy(S) = −p+·log2(p+) − p−·log2(p−)",
      "Entropy(S) = p+ − p−",
      "Entropy(S) = (p+ + p−) / 2"
    ],
    correctAnswer: "Entropy(S) = −p+·log2(p+) − p−·log2(p−)",
    explanation: "Information theory defines entropy of a binary sample as: Entropy(S) = −p+·log2(p+) − p−·log2(p−)."
  },
  {
    id: 30,
    question: "A sample set S contains 12 positive and 4 negative examples (16 total). What is Entropy(S)? (round to 2 decimals)",
    options: [
      "0.81",
      "0.94",
      "0.65",
      "1.00"
    ],
    correctAnswer: "0.81",
    explanation: "p+ = 12/16 = 0.75, p− = 4/16 = 0.25. Entropy(S) = −0.75·log2(0.75) − 0.25·log2(0.25) = −0.75×(−0.415) − 0.25×(−2) = 0.311 + 0.500 = 0.811 ≈ 0.81."
  },
  {
    id: 31,
    question: "Reduced-Error Pruning is a post-pruning technique that works by:",
    options: [
      "Using the entire training set for both growing and validating the tree, with no separate validation data",
      "Partitioning the data into a 'grow' set and a 'validation' set, building a full tree on the grow set, and then repeatedly pruning the non-leaf node whose removal gives the greatest increase in validation accuracy, until accuracy no longer improves",
      "Never removing any node from the fully-grown tree under any circumstance",
      "Pruning based purely on alphabetical attribute names, without using any data"
    ],
    correctAnswer: "Partitioning the data into a 'grow' set and a 'validation' set, building a full tree on the grow set, and then repeatedly pruning the non-leaf node whose removal gives the greatest increase in validation accuracy, until accuracy no longer improves",
    explanation: "In reduced-error pruning, the dataset is split into training and validation sets. Subtrees are tentatively pruned to a majority leaf and kept pruned if accuracy on the validation set does not decrease."
  },

  // Section C: Information Gain & Gini Index (Q32–Q37)
  {
    id: 32,
    question: "Information Gain, Gain(S,A), for splitting sample S on attribute A is defined as:",
    options: [
      "Entropy(S) multiplied by the number of distinct values of A",
      "The expected reduction in entropy due to partitioning S on A: Gain(S,A) = Entropy(S) − Σv (|Sv|/|S|)·Entropy(Sv)",
      "The sum of the entropies of all the subsets Sv",
      "The maximum entropy among all the subsets Sv"
    ],
    correctAnswer: "The expected reduction in entropy due to partitioning S on A: Gain(S,A) = Entropy(S) − Σv (|Sv|/|S|)·Entropy(Sv)",
    explanation: "Information gain subtracts the weighted average entropy of the resulting subsets from the original entropy of sample S."
  },
  {
    id: 33,
    question: "For the PlayTennis-style dataset, Entropy(S) = 0.940 for S=[9+,5−]. Splitting on 'Humidity' gives: Humidity=High → 7 examples with entropy 0.985; Humidity=Normal → 7 examples with entropy 0.592. What is Gain(S, Humidity)? (round to 3 decimals)",
    options: [
      "0.151",
      "0.246",
      "0.048",
      "0.325"
    ],
    correctAnswer: "0.151",
    explanation: "Gain(S, Humidity) = 0.940 − (7/14)×0.985 − (7/14)×0.592 = 0.940 − 0.4925 − 0.296 = 0.940 − 0.7885 = 0.151."
  },
  {
    id: 34,
    question: "Using the sample S from Q30 (12+, 4−; Entropy(S)=0.81), suppose splitting on attribute A gives: Branch1 = [8+, 1−] (9 examples, Entropy ≈ 0.50) and Branch2 = [4+, 3−] (7 examples, Entropy ≈ 0.99). What is Gain(S, A)? (round to 2 decimals)",
    options: [
      "0.10",
      "0.25",
      "0.02",
      "0.38"
    ],
    correctAnswer: "0.10",
    explanation: "Gain(S, A) = Entropy(S) − (9/16)×0.50 − (7/16)×0.99 = 0.81 − 0.5625×0.50 − 0.4375×0.99 = 0.81 − 0.281 − 0.433 = 0.81 − 0.714 ≈ 0.10."
  },
  {
    id: 35,
    question: "The GINI Index of a node (a measure of node impurity) is defined as:",
    options: [
      "GINI(Node) = Σ [p(c)]² over all classes c",
      "GINI(Node) = 1 − Σ [p(c)]² over all classes c",
      "GINI(Node) = 1 + Σ [p(c)]²",
      "GINI(Node) = max over c of p(c)"
    ],
    correctAnswer: "GINI(Node) = 1 − Σ [p(c)]² over all classes c",
    explanation: "GINI impurity measures the probability of misclassifying a randomly selected element if labeled randomly according to the class distribution: GINI = 1 − Σ [p(c)]²."
  },
  {
    id: 36,
    question: "What is the Gini index of a node containing 90 positive and 60 negative examples (150 total)?",
    options: [
      "0.48",
      "0.52",
      "0.36",
      "0.64"
    ],
    correctAnswer: "0.48",
    explanation: "p+ = 90/150 = 0.6, p− = 60/150 = 0.4. GINI = 1 − [p+² + p−²] = 1 − [0.6² + 0.4²] = 1 − [0.36 + 0.16] = 1 − 0.52 = 0.48."
  },
  {
    id: 37,
    question: "A split on attribute A produces two children: Child1 has 70 examples (80% positive) and Child2 has 30 examples (30% positive). Using GINIsplit(A) = Σv (|Sv|/|S|)·GINI(Nv), what is GINIsplit(A)?",
    options: [
      "0.35",
      "0.42",
      "0.28",
      "0.50"
    ],
    correctAnswer: "0.35",
    explanation: "GINI(Child1) = 1 − [0.8² + 0.2²] = 1 − 0.68 = 0.32. GINI(Child2) = 1 − [0.3² + 0.7²] = 1 − 0.58 = 0.42. GINIsplit(A) = (70/100)×0.32 + (30/100)×0.42 = 0.224 + 0.126 = 0.35."
  },

  // Section D: Overfitting, Pruning & Model Complexity (Q38–Q45)
  {
    id: 38,
    question: "For a continuous-valued attribute, the 'binary split' approach used in decision trees works by:",
    options: [
      "Always using the mean of all the attribute's values as the split point, without testing alternatives",
      "Creating a new boolean attribute Ac = true if A ≤ c (false otherwise), after considering all possible thresholds c and choosing the best cut",
      "Always splitting the attribute's range into exactly 4 equal-width intervals",
      "Converting the continuous attribute to a categorical one using only its rank, ignoring the actual values"
    ],
    correctAnswer: "Creating a new boolean attribute Ac = true if A ≤ c (false otherwise), after considering all possible thresholds c and choosing the best cut",
    explanation: "Continuous attributes are handled by dynamically defining candidate threshold cuts c, evaluating candidate boolean tests A ≤ c, and selecting the threshold that maximizes information gain."
  },
  {
    id: 39,
    question: "According to the slides, finding the minimal decision tree that is consistent with a given set of training data is:",
    options: [
      "Solvable in polynomial time",
      "NP-hard",
      "Always solvable in O(n log n) time",
      "An undecidable problem"
    ],
    correctAnswer: "NP-hard",
    explanation: "Finding the globally minimal decision tree consistent with training data is known to be NP-hard, which necessitates heuristic greedy algorithms."
  },
  {
    id: 40,
    question: "Since finding the globally optimal decision tree is computationally hard, algorithms like ID3 instead perform:",
    options: [
      "An exhaustive, systematic search over every possible tree",
      "A greedy heuristic search — hill climbing without backtracking",
      "A purely random search with no evaluation criterion at all",
      "A brute-force search that is guaranteed to find the global optimum"
    ],
    correctAnswer: "A greedy heuristic search — hill climbing without backtracking",
    explanation: "ID3 executes a top-down greedy search (hill climbing), picking the locally best attribute at each node without ever backtracking."
  },
  {
    id: 41,
    question: "A hypothesis h is said to 'overfit' the training data if:",
    options: [
      "h has a larger error than another hypothesis h′ on both the training data and the test data",
      "There exists another hypothesis h′ such that h has smaller error than h′ on the training data, but h has larger error than h′ on the test data",
      "h and h′ always have identical training error",
      "Overfitting can only occur when the training set is extremely large"
    ],
    correctAnswer: "There exists another hypothesis h′ such that h has smaller error than h′ on the training data, but h has larger error than h′ on the test data",
    explanation: "A hypothesis h overfits when an alternative hypothesis h' exists that performs worse on the training set but achieves lower error on unseen test instances."
  },
  {
    id: 42,
    question: "Which of the following are cited in the slides as common causes of overfitting?\nI. Noise present in the training data\nII. The model/tree being based on insufficient (limited) training data\nIII. Using a separate validation set during training\nIV. Pruning the tree after it is fully built",
    options: [
      "I and II only",
      "I and III only",
      "II and IV only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I and II only",
    explanation: "Noise in data and small/insufficient sample size are the primary causes of overfitting. Validation sets and pruning are remedies to combat overfitting."
  },
  {
    id: 43,
    question: "As model/tree complexity increases, what typically happens to the training error and the test (generalization) error?",
    options: [
      "Both training and test error keep decreasing indefinitely as complexity grows",
      "Training error keeps decreasing (often reaching 0), while test error decreases initially but then starts increasing beyond a certain complexity — this is overfitting",
      "Both training and test error increase together as complexity grows",
      "Training error increases while test error stays exactly constant"
    ],
    correctAnswer: "Training error keeps decreasing (often reaching 0), while test error decreases initially but then starts increasing beyond a certain complexity — this is overfitting",
    explanation: "Training error decreases monotonically with model complexity, but test error forms a characteristic U-curve: decreasing at first, then increasing as overfitting takes over."
  },
  {
    id: 44,
    question: "'Underfitting' is best described as the situation where:",
    options: [
      "The model is too simple, resulting in both high training error and high test error",
      "The model fits the training data perfectly but performs poorly on test data",
      "The model achieves zero error on both training and test data",
      "The model has far too many parameters relative to the amount of data"
    ],
    correctAnswer: "The model is too simple, resulting in both high training error and high test error",
    explanation: "Underfitting occurs when the hypothesis space is too restrictive or the model is too simple, leading to high error on both training and generalization data."
  },
  {
    id: 45,
    question: "Which of the following are valid Pre-pruning (early stopping) conditions for decision tree induction?\nI. Stop growing the tree if all instances at a node already belong to the same class\nII. Stop if the number of instances at a node falls below a user-specified threshold\nIII. Grow the tree fully first, then remove nodes afterward\nIV. Stop if expanding the current node does not improve an impurity measure such as information gain or Gini",
    options: [
      "I, II, and IV",
      "I, II, and III",
      "II, III, and IV",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and IV",
    explanation: "Pre-pruning halts expansion early using conditions I, II, and IV. Statement III describes post-pruning, not pre-pruning."
  }
];

// Metadata & Configuration for all available weeks
const WEEKS_DATA = {
  1: {
    id: 1,
    title: "Week 1",
    subheading: "Week 1 • Foundations & Evaluation",
    name: "Foundations & Evaluation",
    heroBadge: "46 Questions Available",
    heroTitle: "Prepare Your Practice Session",
    heroDesc: "Test your understanding on Mitchell's definition, Supervised/Unsupervised paradigms, Inductive Bias, Precision/Recall/F1, Overfitting, and K-Fold Cross Validation.",
    topics: ["Mitchell's Definition", "Supervised / Unsupervised", "Inductive Bias", "Precision, Recall & F1", "Confusion Matrix", "K-Fold Cross Validation"],
    totalQuestions: WEEK1_QUESTIONS.length,
    questions: WEEK1_QUESTIONS
  },
  2: {
    id: 2,
    title: "Week 2",
    subheading: "Week 2 • Linear Regression & Decision Trees",
    name: "Linear Regression & Decision Trees",
    heroBadge: "45 Questions Available",
    heroTitle: "Prepare Your Practice Session",
    heroDesc: "Test your understanding on Linear Regression, Least Squares (LMS), Gradient Descent (Batch & SGD), Decision Trees (ID3), Information Gain, Gini Index, and Pruning.",
    topics: ["Linear Regression & LMS", "Gradient Descent / SGD", "Decision Trees & ID3", "Entropy & Information Gain", "GINI Index & Splitting", "Overfitting & Pruning"],
    totalQuestions: WEEK2_QUESTIONS.length,
    questions: WEEK2_QUESTIONS
  }
};

// Global reference for backwards compatibility
let CURRENT_WEEK = 1;
let QUESTIONS_BANK = WEEK1_QUESTIONS;
