// NPTEL Introduction to Machine Learning Question Bank
// Module 1 (Week 1): Foundations & Evaluation (Prof. Sudeshna Sarkar, IIT Kharagpur)
// Module 2 (Week 2): Linear Regression & Decision Trees (Prof. Sudeshna Sarkar, IIT Kharagpur)

const WEEK1_QUESTIONS = [
  {
    id: 1,
    question: "According to Mitchell's definition, a program is said to 'learn' if its performance at tasks in T, as measured by P, improves with which of the following?",
    options: [
      "The size of the hypothesis space",
      "Experience E",
      "The number of features",
      "The learning rate"
    ],
    correctAnswer: "Experience E",
    explanation: "Mitchell's classic definition: a program learns from experience E with respect to task T and performance measure P if its performance at T, as measured by P, improves with E."
  },
  {
    id: 2,
    question: "A data scientist has unlabelled sensor readings and wants the model to learn purely from trial-and-error feedback (reward/punishment) while interacting with a live system. Which learning paradigm fits best?",
    options: [
      "Supervised Learning",
      "Unsupervised Learning",
      "Reinforcement Learning",
      "Semi-Supervised Learning"
    ],
    correctAnswer: "Reinforcement Learning",
    explanation: "Reinforcement learning determines actions based on rewards and punishments received from an environment, not from pre-labelled data."
  },
  {
    id: 3,
    question: "In the semi-supervised learning diagram from the slides, what additional data (beyond labeled data) is used to help find a better classification plane?",
    options: [
      "Synthetic labeled data generated by another classifier",
      "Unlabeled data from the same distribution",
      "Data from a completely different domain",
      "Only the test set"
    ],
    correctAnswer: "Unlabeled data from the same distribution",
    explanation: "Semi-supervised learning uses both labeled and unlabeled data (from the same distribution) to improve the learned decision boundary compared to using labeled data alone."
  },
  {
    id: 4,
    question: "In the Reinforcement Learning diagram (Agent–Environment loop), which two signals does the Environment send back to the Agent after it takes an action a_t?",
    options: [
      "State s_t+1 and Reward r_t+1",
      "Only the reward",
      "A new action and a label",
      "The target function and a feature vector"
    ],
    correctAnswer: "State s_t+1 and Reward r_t+1",
    explanation: "The environment responds to an action with the next state (s_t+1) and a reward (r_t+1), which the agent uses to update its policy."
  },
  {
    id: 5,
    question: "Which of the following is the best example of an Unsupervised Learning task?",
    options: [
      "Predicting house prices from area and location",
      "Grouping news articles into topics without any predefined categories",
      "Classifying emails as spam or not spam using labeled training data",
      "Training a robot arm using reward signals"
    ],
    correctAnswer: "Grouping news articles into topics without any predefined categories",
    explanation: "Grouping/clustering data without pre-existing labels is the defining example of unsupervised learning."
  },
  {
    id: 6,
    question: "Which statement correctly distinguishes Classification from Regression?",
    options: [
      "Classification predicts continuous values; Regression predicts discrete labels",
      "Classification predicts a discrete/categorical target Y; Regression predicts a continuous target Y",
      "Both always predict continuous values but classification uses more features",
      "Regression cannot use numerical features"
    ],
    correctAnswer: "Classification predicts a discrete/categorical target Y; Regression predicts a continuous target Y",
    explanation: "As stated in the slides: classification is used when Y is discrete, and regression is used when Y is continuous."
  },
  {
    id: 7,
    question: "A dataset field records temperature as 'Low', 'Medium', 'High'. What type of feature is this?",
    options: [
      "Categorical (nominal)",
      "Ordinal",
      "Integer-valued",
      "Real-valued"
    ],
    correctAnswer: "Ordinal",
    explanation: "'Low/Medium/High' has a natural order, so it is an ordinal feature (like 'large/medium/small' in the slides), not a plain categorical (nominal) one."
  },
  {
    id: 8,
    question: "In the terminology used in the slides, what is a 'Feature Vector'?",
    options: [
      "A set of all possible labels",
      "An n-dimensional vector of features that represents an object",
      "The function that maps features to labels",
      "A single scalar performance score"
    ],
    correctAnswer: "An n-dimensional vector of features that represents an object",
    explanation: "Feature vector: n-dimensional vector of numerical features that represent some object, e.g. d = <x1, x2, ..., xn>."
  },
  {
    id: 9,
    question: "What is the 'Instance Space X' as defined in the slides?",
    options: [
      "The set of all training examples only",
      "The set of all possible objects describable by the features",
      "The set of all hypotheses a learner can produce",
      "The set of all class labels"
    ],
    correctAnswer: "The set of all possible objects describable by the features",
    explanation: "Instance Space X is defined as the set of all possible objects describable by the features — much larger than just the training set."
  },
  {
    id: 10,
    question: "An 'Example (x, y)' as used in the slides refers to:",
    options: [
      "Two different instances being compared",
      "An instance x together with its label y = f(x)",
      "A hypothesis paired with its accuracy",
      "A feature paired with its data type"
    ],
    correctAnswer: "An instance x together with its label y = f(x)",
    explanation: "An example is an instance x with its label y=f(x) — the (input, output) pair used for training/testing."
  },
  {
    id: 11,
    question: "A learner restricts itself to only using decision rules of the form 'IF condition THEN class', ignoring all other possible functions. This is an example of which kind of inductive bias?",
    options: [
      "Preference bias",
      "Restriction bias",
      "Variance bias",
      "Sample bias"
    ],
    correctAnswer: "Restriction bias",
    explanation: "Restriction bias limits the hypothesis space itself (e.g., only considering rule-based hypotheses), as opposed to preference bias which orders hypotheses within an unrestricted space."
  },
  {
    id: 12,
    question: "Among two hypotheses that are both perfectly consistent with the training data, a learner always picks the one that is simpler / shorter to describe. This illustrates which principle?",
    options: [
      "Maximum margin principle",
      "Occam's Razor",
      "Cross-validation",
      "The bias-variance decomposition"
    ],
    correctAnswer: "Occam's Razor",
    explanation: "Occam's Razor: the simplest hypothesis consistent with the data is preferred — a classic example of inductive (preference) bias."
  },
  {
    id: 13,
    question: "If a dataset has 5 independent boolean input features, how many unique Boolean functions can theoretically be defined over this feature space?",
    options: [
      "2^5 = 32",
      "2^10 = 1,024",
      "2^32 = 4,294,967,296",
      "2^16 = 65,536"
    ],
    correctAnswer: "2^32 = 4,294,967,296",
    explanation: "Number of Boolean functions over N boolean features = 2^(2^N). For N=5, this is 2^(2^5) = 2^32 = 4,294,967,296."
  },
  {
    id: 14,
    question: "If a dataset has only 2 independent boolean input features, how many unique Boolean functions can theoretically be defined over this feature space?",
    options: [
      "4",
      "8",
      "16",
      "32"
    ],
    correctAnswer: "16",
    explanation: "Formula: 2^(2^N). With N=2, this gives 2^(2^2) = 2^4 = 16 possible Boolean functions."
  },
  {
    id: 15,
    question: "Which of the following best defines the Hypothesis Space H in supervised learning?",
    options: [
      "The set of all training examples available",
      "The set of all functions the learning algorithm is allowed to consider while approximating the target function f",
      "The subset of features selected after feature selection",
      "The confusion matrix computed on the test set"
    ],
    correctAnswer: "The set of all functions the learning algorithm is allowed to consider while approximating the target function f",
    explanation: "Hypothesis Space H is the set of functions we allow for approximating f; the learner searches within this space (Input: training set S ⊆ X, Output: a hypothesis h ∈ H)."
  },
  {
    id: 16,
    question: "Which is an example of a 'preference bias' rather than a 'restriction bias'?",
    options: [
      "Only allowing linear decision boundaries",
      "Only allowing decision trees of depth ≤ 3",
      "Among all consistent decision trees, preferring the shortest one (Occam's Razor)",
      "Only allowing conjunctive Boolean concepts"
    ],
    correctAnswer: "Among all consistent decision trees, preferring the shortest one (Occam's Razor)",
    explanation: "Restriction bias limits which hypotheses are even considered (e.g., only linear, only shallow trees, only conjunctions). Preference bias instead ranks/orders hypotheses within a space that isn't restricted — Occam's Razor is the classic preference bias example."
  },
  {
    id: 17,
    question: "SVM's approach of choosing the decision boundary that maximizes the margin between two classes is an example of which type of inductive bias?",
    options: [
      "Restriction bias",
      "Maximum margin bias (a preference bias)",
      "Minimum description length bias",
      "No bias at all"
    ],
    correctAnswer: "Maximum margin bias (a preference bias)",
    explanation: "Maximum margin is explicitly listed as a type of inductive bias: when drawing a boundary between two classes, attempt to maximize the width of the boundary (used in SVMs)."
  },
  {
    id: 18,
    question: "The 'Inductive Learning Hypothesis' states that:",
    options: [
      "Any hypothesis that fits the training data will always fit unseen data perfectly",
      "A hypothesis that approximates the target function well over a sufficiently large training set will also approximate it well over other unobserved examples",
      "Inductive learning can only work with linear functions",
      "More features always lead to better generalization"
    ],
    correctAnswer: "A hypothesis that approximates the target function well over a sufficiently large training set will also approximate it well over other unobserved examples",
    explanation: "This is the direct definition given in the slides of the Inductive Learning Hypothesis."
  },
  {
    id: 19,
    question: "A binary classifier is evaluated on 400 samples: 250 actual positives, 150 actual negatives. It predicts 220 positives total, of which 200 are correctly predicted positive. What is the Recall of this classifier?",
    options: [
      "80% (200/250)",
      "90.9% (200/220)",
      "50% (200/400)",
      "75% (150/200)"
    ],
    correctAnswer: "80% (200/250)",
    explanation: "Recall = TP / (Actual Positives) = 200 / 250 = 0.80 = 80%."
  },
  {
    id: 20,
    question: "Using the same classifier as above (220 predicted positive, 200 of which are truly positive), what is the Precision?",
    options: [
      "80.0%",
      "≈90.9% (200/220)",
      "75.5%",
      "85.0%"
    ],
    correctAnswer: "≈90.9% (200/220)",
    explanation: "Precision = TP / (Predicted Positives) = 200 / 220 ≈ 0.909 = 90.9%."
  },
  {
    id: 21,
    question: "A model has Precision = 0.8 and Recall = 0.5. What is its F1-Score (to 2 decimal places)?",
    options: [
      "0.65",
      "0.62",
      "0.40",
      "0.70"
    ],
    correctAnswer: "0.62",
    explanation: "F1 = 2 * (P * R) / (P + R) = 2 * (0.8 * 0.5) / (0.8 + 0.5) = 0.8 / 1.3 ≈ 0.6154, rounded to 0.62."
  },
  {
    id: 22,
    question: "In a confusion matrix, if TP=50, FP=10, FN=20, TN=120, what is the Accuracy?",
    options: [
      "80%",
      "85% ((50+120)/200)",
      "75%",
      "90%"
    ],
    correctAnswer: "85% ((50+120)/200)",
    explanation: "Accuracy = (TP + TN) / (TP + TN + FP + FN) = (50 + 120) / 200 = 170 / 200 = 0.85 = 85%."
  },
  {
    id: 23,
    question: "In a confusion matrix, if TP=50, FP=10, FN=20, TN=120, what is the False Positive Rate (FP Rate)?",
    options: [
      "10/130 ≈ 7.7%",
      "10/60 ≈ 16.7%",
      "10/200 = 5.0%",
      "20/140 ≈ 14.3%"
    ],
    correctAnswer: "10/130 ≈ 7.7%",
    explanation: "FP Rate = FP / Actual Negatives = FP / (FP + TN) = 10 / (10 + 120) = 10 / 130 ≈ 0.0769 = 7.7%."
  },
  {
    id: 24,
    question: "Which metric answers the question: 'Of all instances the model predicted as positive, how many were actually positive?'",
    options: [
      "Recall",
      "Precision",
      "Accuracy",
      "FP Rate"
    ],
    correctAnswer: "Precision",
    explanation: "Precision = TP / (TP + FP) — the fraction of predicted positives that are truly positive."
  },
  {
    id: 25,
    question: "Which metric answers the question: 'Of all the actual positive instances, how many did the model correctly identify?'",
    options: [
      "Precision",
      "Recall (also called TP rate/Sensitivity)",
      "Specificity",
      "F1-Score only"
    ],
    correctAnswer: "Recall (also called TP rate/Sensitivity)",
    explanation: "Recall = TP / P (actual positives) — this is also called the True Positive Rate or Sensitivity."
  },
  {
    id: 26,
    question: "Why is Accuracy often a misleading metric on highly imbalanced datasets (e.g., 990 negatives, 10 positives)?",
    options: [
      "Accuracy cannot be computed for imbalanced data at all",
      "A model that always predicts 'negative' would still get 99% accuracy while catching zero positives",
      "Accuracy always equals Precision in imbalanced data",
      "Imbalanced datasets have no negatives"
    ],
    correctAnswer: "A model that always predicts 'negative' would still get 99% accuracy while catching zero positives",
    explanation: "With heavy class imbalance, a trivial always-predict-majority-class model scores very high accuracy despite being useless for detecting the minority (often more important) class — that's why Precision/Recall/F1 are preferred there."
  },
  {
    id: 27,
    question: "Which of the following correctly characterizes an Underfit model?",
    options: [
      "Low bias, high variance",
      "High bias, low variance — the model is too simple to capture the pattern",
      "High training accuracy, low test accuracy",
      "Zero error on both training and test data"
    ],
    correctAnswer: "High bias, low variance — the model is too simple to capture the pattern",
    explanation: "Underfitting occurs when the model is too simple: it shows high bias and low variance, with high error on both training and test sets."
  },
  {
    id: 28,
    question: "A decision tree is grown until every leaf is pure (100% training accuracy) but performs poorly on unseen data. What does this indicate about its bias and variance?",
    options: [
      "Low bias, high variance (overfitting)",
      "High bias, low variance (underfitting)",
      "Both bias and variance are zero",
      "This indicates a data leakage problem, not overfitting"
    ],
    correctAnswer: "Low bias, high variance (overfitting)",
    explanation: "A model that perfectly fits training data but generalizes poorly is overfitting: it has low bias (fits training data well) but high variance (very sensitive to the specific training set)."
  },
  {
    id: 29,
    question: "What does the 'Variance' component of generalization error measure?",
    options: [
      "How much the average model over all training sets differs from the true model",
      "How much models trained on different training sets differ from each other",
      "The number of features used by the model",
      "The total training time of the model"
    ],
    correctAnswer: "How much models trained on different training sets differ from each other",
    explanation: "Variance measures how much models estimated from different training sets differ from each other — high variance means the model is highly sensitive to the particular training sample."
  },
  {
    id: 30,
    question: "Model A has low bias and high variance. Model B has high bias and low variance. Which statement is most accurate?",
    options: [
      "Model A likely overfits the training data; Model B likely underfits it",
      "Model A always has lower test error than Model B",
      "Both models have identical generalization error",
      "Model B is guaranteed to memorize the training set"
    ],
    correctAnswer: "Model A likely overfits the training data; Model B likely underfits it",
    explanation: "Low bias/high variance is the classic signature of overfitting, while high bias/low variance is the classic signature of underfitting."
  },
  {
    id: 31,
    question: "Which of the following is NOT listed among the causes of error in machine learning according to the slides?",
    options: [
      "Limited representation (representation bias)",
      "Limited search (search bias)",
      "Limited data (variance)",
      "Excessive computational power of the hardware"
    ],
    correctAnswer: "Excessive computational power of the hardware",
    explanation: "The slides list limited representation, limited search, limited data (variance), and limited/noisy features as causes of learning error — hardware power is not one of them."
  },
  {
    id: 32,
    question: "Which combination of statements about overfitting is correct?\nI. Overfitting leads to poor generalization on unseen data.\nII. Overfitting usually results in low training error.\nIII. Overfitting always improves test accuracy.",
    options: [
      "I only",
      "I and II only",
      "II and III only",
      "I, II and III"
    ],
    correctAnswer: "I and II only",
    explanation: "Overfitting causes poor generalization (I, true) and typically very low training error since the model fits the training data closely (II, true), but it does NOT improve test accuracy — in fact it usually hurts it (III, false)."
  },
  {
    id: 33,
    question: "Why does a single train/test split sometimes give an unreliable estimate of a model's true performance?",
    options: [
      "Because train/test splits are illegal in machine learning",
      "Because the small test set can have high variance in its estimate of error",
      "Because train/test splits always overestimate accuracy",
      "Because test sets cannot contain labels"
    ],
    correctAnswer: "Because the small test set can have high variance in its estimate of error",
    explanation: "With a single, possibly small, test set, the estimate of error has high variance — different random splits can give quite different error estimates."
  },
  {
    id: 34,
    question: "In 10-fold cross-validation, what fraction of the data is used as the test/validation set in each round?",
    options: [
      "1/2",
      "1/5",
      "1/10",
      "All of the data"
    ],
    correctAnswer: "1/10",
    explanation: "In k-fold cross-validation, 1/k of the data is held out as the test set each round; for k=10, that is 1/10 of the data."
  },
  {
    id: 35,
    question: "What is the main advantage of k-fold cross-validation over a single fixed validation set?",
    options: [
      "It uses all the available data for both training and testing across different rounds, reducing wasted data",
      "It requires no computation at all",
      "It removes the need for a test set entirely",
      "It guarantees zero overfitting"
    ],
    correctAnswer: "It uses all the available data for both training and testing across different rounds, reducing wasted data",
    explanation: "A single validation split 'fails to use all the available data' (as the slides note); k-fold cross-validation rotates which portion is held out so every example is eventually used for both training and testing, giving a more robust estimate."
  },
  {
    id: 36,
    question: "The final reported score in k-fold cross-validation is typically computed as:",
    options: [
      "The score on the very last fold only",
      "The maximum score across all folds",
      "The average of the test-set scores across all k rounds",
      "The score on the full, unsplit dataset"
    ],
    correctAnswer: "The average of the test-set scores across all k rounds",
    explanation: "As shown in the slides: Final Accuracy = Average(Round 1, Round 2, ..., Round k)."
  },
  {
    id: 37,
    question: "What is the key difference between 'sample error' and 'true error' of a hypothesis?",
    options: [
      "Sample error is computed on data sample S; true error is the probability of misclassifying an instance drawn from the whole distribution D",
      "They are always numerically identical",
      "True error can only be computed for regression, sample error only for classification",
      "Sample error requires infinite data, true error requires only one example"
    ],
    correctAnswer: "Sample error is computed on data sample S; true error is the probability of misclassifying an instance drawn from the whole distribution D",
    explanation: "Sample error is measured on a finite sample S; true error (error_D) is the probability of misclassification over the entire underlying distribution D, which sample error only estimates."
  },
  {
    id: 38,
    question: "Why do we care about performance on the underlying distribution D rather than just on the training data?",
    options: [
      "Because training data is always corrupted",
      "Because the goal of learning is to generalize well to new, unseen data drawn from D, not just memorize training data",
      "Because training data has no labels",
      "Because the distribution D is always identical to the training set"
    ],
    correctAnswer: "Because the goal of learning is to generalize well to new, unseen data drawn from D, not just memorize training data",
    explanation: "As emphasized in the slides: 'we care about performance on the distribution, not the training data' — generalization to unseen data is the real objective."
  },
  {
    id: 39,
    question: "According to the machine learning history timeline in the slides, which decade is Rosenblatt's Perceptron and Minsky & Papert's proof of its limitations associated with?",
    options: [
      "1950s",
      "1960s",
      "1970s",
      "1980s"
    ],
    correctAnswer: "1960s",
    explanation: "The 1960s slide lists: Neural network — Rosenblatt's perceptron; Minsky & Papert prove limitations of Perceptron."
  },
  {
    id: 40,
    question: "Which of these milestones is correctly matched to its year according to the slides?",
    options: [
      "1997 — Deep Blue beats Garry Kasparov",
      "1994 — Watson wins Jeopardy",
      "2009 — Deep Blue beats Garry Kasparov",
      "2011 — Google builds a self-driving car"
    ],
    correctAnswer: "1997 — Deep Blue beats Garry Kasparov",
    explanation: "The slides list: 1994 — Self-driving car road test; 1997 — Deep Blue beats Garry Kasparov; 2009 — Google builds self-driving car; 2011 — Watson wins Jeopardy."
  },
  {
    id: 41,
    question: "Which of the following is NOT listed in the slides as a reason for ML's recent surge in popularity?",
    options: [
      "New software/algorithms (e.g., deep learning)",
      "New hardware (GPUs)",
      "Cloud enabled computing and availability of Big Data",
      "Reduction in the number of available features"
    ],
    correctAnswer: "Reduction in the number of available features",
    explanation: "The slides list new software/algorithms, new hardware (GPUs), cloud enablement, and availability of Big Data as reasons for ML's popularity — not a reduction in features."
  },
  {
    id: 42,
    question: "In the 'Algorithmic solution vs Machine learning solution' diagram, what are the two inputs to the computer in the Machine Learning solution (as opposed to the Algorithmic solution)?",
    options: [
      "Data and Program",
      "Data and Output",
      "Program and Output",
      "Only Data"
    ],
    correctAnswer: "Data and Output",
    explanation: "In the ML solution, the computer takes Data and Output (desired results) as input and produces the Program (model) as output — reversing the classical algorithmic approach of Data+Program -> Output."
  },
  {
    id: 43,
    question: "According to the 'Design a Learner' framework in the slides, what is the correct order of steps?",
    options: [
      "Choose learning algorithm -> Choose training experience -> Choose target function -> Choose representation",
      "Choose the training experience -> Choose the target function -> Choose how to represent the target function -> Choose a learning algorithm to infer it",
      "Choose representation -> Choose training experience -> Choose learning algorithm -> Choose target function",
      "There is no defined order; all steps happen simultaneously"
    ],
    correctAnswer: "Choose the training experience -> Choose the target function -> Choose how to represent the target function -> Choose a learning algorithm to infer it",
    explanation: "The slides list these four steps in this exact order for designing a learner."
  },
  {
    id: 44,
    question: "In the Classification Learning framework (Task T, Performance metric P, Experience E), what does 'Experience E' typically consist of?",
    options: [
      "A set of unlabeled instances only",
      "A set of labeled examples (x, y) sampled from a fixed distribution D",
      "The set of all possible hypotheses",
      "The accuracy score of the final model"
    ],
    correctAnswer: "A set of labeled examples (x, y) sampled from a fixed distribution D",
    explanation: "Experience E is defined as a set of labeled examples (x,y) where y is the true label for x, ideally sampled from a fixed distribution D."
  },
  {
    id: 45,
    question: "For the task of 'finding entity names in text', what would typically serve as the Instance and Label according to the classification learning table in the slides?",
    options: [
      "Instance: a whole document; Label: the document's topic",
      "Instance: a word in context (e.g., capitalization, nearby words); Label: {first, later, outside}",
      "Instance: an image; Label: {0,1}",
      "Instance: lab readings; Label: risk of heart disease"
    ],
    correctAnswer: "Instance: a word in context (e.g., capitalization, nearby words); Label: {first, later, outside}",
    explanation: "The slides' example table lists: Task = finding entity names in text; Instance = a word in context (capitalized, nearby words, ...); Labels = {first, later, outside}."
  },
  {
    id: 46,
    question: "Why is 'Diagnosing a disease' a good example of a task requiring historical medical records as Data (per the slides)?",
    options: [
      "Because the output labels (disease/no disease) can only be obtained by waiting and observing outcomes over time, which historical records capture",
      "Because medical records never contain any useful features",
      "Because diagnosis tasks never need any training data",
      "Because this is purely an unsupervised learning task"
    ],
    correctAnswer: "Because the output labels (disease/no disease) can only be obtained by waiting and observing outcomes over time, which historical records capture",
    explanation: "The slides note that for medical diagnosis, data comes from historical medical records, and learning involves determining which future patients will respond best to which treatments — i.e., learning from past labeled outcomes."
  }
];

// Week 2 Question Bank: Linear Regression & Decision Trees (45 Questions)
// Sourced directly from Module 2 Practice Questions with Answers (Prof. Sudeshna Sarkar, IIT Kharagpur)
const WEEK2_QUESTIONS = [
  // Section A: Linear Regression (Q1–Q21)
  {
    id: 1,
    question: "In regression, the predicted output variable is:",
    options: [
      "Discrete/categorical",
      "Continuous",
      "Always binary (0/1)",
      "Always a time-series"
    ],
    correctAnswer: "Continuous",
    explanation: "Regression problems predict a continuous-valued output, unlike classification which predicts discrete class labels."
  },
  {
    id: 2,
    question: "Which loss function is used in the polynomial curve-fitting example to measure how well a curve fits the data?",
    options: [
      "Absolute error",
      "Squared error in the prediction of y(x) from x",
      "Hinge loss",
      "Cross-entropy loss"
    ],
    correctAnswer: "Squared error in the prediction of y(x) from x",
    explanation: "The slides state a loss function that measures the squared error in the prediction of y(x) from x."
  },
  {
    id: 3,
    question: "In (regularized) linear regression, overfitting is typically characterized by:",
    options: [
      "Very small (near-zero) weights",
      "Large weights, making the model overly sensitive to the training data",
      "Weights that are always exactly zero",
      "Weights that are always positive"
    ],
    correctAnswer: "Large weights, making the model overly sensitive to the training data",
    explanation: "The slides note that overfitting in a linear regression model is characterized by large weights — regularization penalizes large weights to control this."
  },
  {
    id: 4,
    question: "In the simple linear regression equation E(y) = b0 + b1x, what does b0 (the intercept) represent?",
    options: [
      "The slope of the regression line",
      "The predicted value of y when x = 0",
      "The random error term",
      "The correlation coefficient between x and y"
    ],
    correctAnswer: "The predicted value of y when x = 0",
    explanation: "b0 represents the y-intercept, which is the predicted value of y when the predictor variable x equals 0."
  },
  {
    id: 5,
    question: "In the same equation E(y) = b0 + b1x, what does b1 (the slope) represent?",
    options: [
      "The intercept of the line",
      "The change in y for a one-unit change in x",
      "The residual error",
      "The sample size"
    ],
    correctAnswer: "The change in y for a one-unit change in x",
    explanation: "b1 represents the slope of the line, which indicates the change in y for a one-unit increase in x."
  },
  {
    id: 6,
    question: "In the regression model Y = β0 + β1x1 + ε, which term denotes the random error associated with each observation?",
    options: [
      "β0",
      "β1",
      "x1",
      "ε"
    ],
    correctAnswer: "ε",
    explanation: "ε denotes the random unobserved error term associated with each observation."
  },
  {
    id: 7,
    question: "Given 5 data points where X = house size (in 100s of sq. ft.) and Y = price (in $1000s):\nX: 1, 2, 3, 4, 5 | Y: 2, 4, 5, 4, 5\nUsing b1 = (n·Σxy − Σx·Σy) / (n·Σx² − (Σx)²), find the slope b1 (round to 2 decimals).",
    options: [
      "0.60",
      "0.45",
      "1.20",
      "0.80"
    ],
    correctAnswer: "0.60",
    explanation: "n = 5, Σx = 1+2+3+4+5 = 15, Σy = 2+4+5+4+5 = 20, Σxy = 2+8+15+16+25 = 66, Σx² = 1+4+9+16+25 = 55. b1 = (5×66 − 15×20) / (5×55 − 15²) = (330 − 300) / (275 − 225) = 30 / 50 = 0.60."
  },
  {
    id: 8,
    question: "Using the same data as Q7 and b0 = (Σy − b1·Σx) / n, find the intercept b0 (round to 2 decimals).",
    options: [
      "2.20",
      "1.80",
      "3.10",
      "0.95"
    ],
    correctAnswer: "2.20",
    explanation: "From Q7: Σy = 20, Σx = 15, b1 = 0.60, n = 5. b0 = (20 − 0.60×15) / 5 = (20 − 9) / 5 = 11 / 5 = 2.20. The fitted regression line is Y = 2.20 + 0.60X."
  },
  {
    id: 9,
    question: "In multiple linear regression Yi = b0 + b1X1 + b2X2 + ... + bpXp + e, what does b0 represent?",
    options: [
      "The slope associated with X1",
      "The average value of Y when all the X's are zero (the intercept)",
      "The variance of Y",
      "The total number of predictors p"
    ],
    correctAnswer: "The average value of Y when all the X's are zero (the intercept)",
    explanation: "b0 is the intercept parameter, representing the expected value of Y when all predictor variables X1 through Xp equal zero."
  },
  {
    id: 10,
    question: "Which of the following are standard assumptions made about the random error εi in a regression model?\nI. E(εi) = 0 for i = 1, 2, ..., n\nII. The errors are independent of each other\nIII. The errors are normally distributed with mean 0 and a fixed standard deviation σ\nIV. The errors must always be positive",
    options: [
      "I, II, and III only",
      "I and II only",
      "II and III only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and III only",
    explanation: "The slides list E(εi)=0, independence, and normal distribution N(0,σ) as standard error assumptions. Errors can be positive or negative — assumption IV is false."
  },
  {
    id: 11,
    question: "The least-squares regression line is defined as the line that:",
    options: [
      "Passes through the maximum possible number of data points",
      "Minimizes the sum of the squared vertical (y) distances between the data points and the line",
      "Maximizes the correlation coefficient between x and y",
      "Minimizes the number of features used in the model"
    ],
    correctAnswer: "Minimizes the sum of the squared vertical (y) distances between the data points and the line",
    explanation: "The least-squares method finds the line that minimizes the sum of squared vertical distances (residuals) between observed points and the regression line."
  },
  {
    id: 12,
    question: "The method of least squares chooses b0 and b1 to minimize which quantity, given observations (xi, yi)?",
    options: [
      "Σ|yi − (b0 + b1xi)|",
      "Σ[yi − (b0 + b1xi)]²",
      "Σ(yi − ȳ)",
      "Σ(xi − x̄)²"
    ],
    correctAnswer: "Σ[yi − (b0 + b1xi)]²",
    explanation: "Least squares explicitly minimizes the sum of squared errors (SSE): Σ[yi − (b0 + b1xi)]²."
  },
  {
    id: 13,
    question: "To find the coefficients that minimize the Sum of Squared Errors (SSE) objective function, the standard approach is to:",
    options: [
      "Take partial derivatives of SSE with respect to each coefficient, set them to zero, and solve",
      "Randomly search all possible coefficient values until one works",
      "Use only the maximum values of x and y in the dataset",
      "Always fix b0 = 0 and solve only for b1"
    ],
    correctAnswer: "Take partial derivatives of SSE with respect to each coefficient, set them to zero, and solve",
    explanation: "Setting partial derivatives of SSE with respect to each parameter to zero produces the normal equations, whose solution gives the optimal regression coefficients."
  },
  {
    id: 14,
    question: "Besides the closed-form (matrix inversion) solution, which iterative technique is mentioned for finding the weights in multiple linear regression?",
    options: [
      "K-means clustering",
      "Delta rule, also called the LMS (Least Mean Squares) method",
      "The Apriori algorithm",
      "ID3 decision tree induction"
    ],
    correctAnswer: "Delta rule, also called the LMS (Least Mean Squares) method",
    explanation: "The Delta rule (LMS or Widrow-Hoff learning rule) is an iterative gradient descent technique for finding weights in linear regression."
  },
  {
    id: 15,
    question: "Given hypothesis h(x) = Σβi·xi and cost function J(θ) = (1/2)Σ(h(x(i)) − y(i))², minimizing J(θ) achieves what?",
    options: [
      "Maximizes the count of correctly classified training examples",
      "Finds parameters θ that make predictions h(x) as close as possible to the actual targets y over the training examples",
      "Guarantees zero model bias",
      "Guarantees the smallest possible test error"
    ],
    correctAnswer: "Finds parameters θ that make predictions h(x) as close as possible to the actual targets y over the training examples",
    explanation: "Minimizing J(θ) finds weights θ such that the model predictions h(x) are as close as possible to the true labels y on the training instances."
  },
  {
    id: 16,
    question: "In the gradient descent update rule βj = βj − α·∂J(θ)/∂βj, what does α represent?",
    options: [
      "The number of training iterations",
      "The learning rate (step size)",
      "The number of training examples m",
      "The bias term of the model"
    ],
    correctAnswer: "The learning rate (step size)",
    explanation: "α represents the learning rate (step size), controlling how large a step is taken along the negative gradient direction."
  },
  {
    id: 17,
    question: "Why does gradient descent on the LMS/SSE cost function for linear regression always converge to the global minimum?",
    options: [
      "Because J(θ) is a convex quadratic function with a single global minimum",
      "Because J(θ) is always non-convex, giving many equally good minima",
      "Because the learning rate is always set to exactly 1",
      "Because there is always only one training example"
    ],
    correctAnswer: "Because J(θ) is a convex quadratic function with a single global minimum",
    explanation: "The LMS/SSE cost function is a convex quadratic bowl with only one global minimum, so gradient descent does not get trapped in suboptimal local minima."
  },
  {
    id: 18,
    question: "For a single training example (x, y), what is the LMS parameter update rule?",
    options: [
      "βj = βj − α(y − h(x))xj",
      "βj = βj + α(y − h(x))xj",
      "βj = βj × α(h(x) − y)",
      "βj = α / (y − h(x))"
    ],
    correctAnswer: "βj = βj + α(y − h(x))xj",
    explanation: "The Widrow-Hoff / LMS rule increases βj when the prediction underestimates y: βj = βj + α(y − h(x))xj."
  },
  {
    id: 19,
    question: "What is the key difference between Batch Gradient Descent and Stochastic Gradient Descent (SGD)?",
    options: [
      "Batch GD updates parameters using the entire training set at each step; SGD updates using one training example at a time",
      "Batch GD updates parameters using one training example at a time; SGD uses the entire training set at once",
      "There is no real difference between the two",
      "SGD always converges to a lower final error than Batch GD"
    ],
    correctAnswer: "Batch GD updates parameters using the entire training set at each step; SGD updates using one training example at a time",
    explanation: "Batch GD sums gradients over the entire training set before taking a step, while SGD updates parameters immediately for each individual training example."
  },
  {
    id: 20,
    question: "According to the slides, what problem arises when the Delta rule (which minimizes regression SSE) is applied directly to a classification task?",
    options: [
      "It always produces perfect classification boundaries",
      "It can lead to misclassifications even when the data is linearly separable, since it minimizes regression error rather than maximizing classification accuracy",
      "It only works when there are more than two classes",
      "It guarantees zero training error in every case"
    ],
    correctAnswer: "It can lead to misclassifications even when the data is linearly separable, since it minimizes regression error rather than maximizing classification accuracy",
    explanation: "The Delta rule minimizes squared error, so examples far from the hyperplane produce large penalties even when correctly classified, shifting the decision boundary and causing misclassifications."
  },
  {
    id: 21,
    question: "Fitting a sigmoid/logistic curve (instead of a straight line) to do classification, as shown in the slides, is basically what method?",
    options: [
      "Linear regression",
      "Logistic regression",
      "K-means clustering",
      "Principal Component Analysis"
    ],
    correctAnswer: "Logistic regression",
    explanation: "Logistic regression fits a sigmoid/logistic curve g(z) = 1/(1+e^-z) to constrain predictions between 0 and 1 for classification."
  },

  // Section B: Decision Trees — Basics & ID3 (Q22–Q31)
  {
    id: 22,
    question: "A decision tree classifier is a tree structure made up of which two main types of nodes?",
    options: [
      "Root node and branch node",
      "Decision node and leaf node",
      "Parent node and child node",
      "Input node and output node"
    ],
    correctAnswer: "Decision node and leaf node",
    explanation: "A decision tree consists of internal decision nodes (testing an attribute) and terminal leaf nodes (assigning a class label)."
  },
  {
    id: 23,
    question: "In a decision tree, what does a leaf node represent?",
    options: [
      "A test or choice on some attribute",
      "The classification (or output value) assigned to an example",
      "The root of the tree",
      "A randomly chosen split point"
    ],
    correctAnswer: "The classification (or output value) assigned to an example",
    explanation: "A leaf node specifies the final classification or prediction assigned to instances that traverse down to that node."
  },
  {
    id: 24,
    question: "When choosing which decision tree to generate from training data, a common inductive bias (related to Occam's Razor) is to prefer:",
    options: [
      "The largest, most detailed tree possible",
      "The smallest tree that is consistent with the data",
      "A tree using the maximum possible number of leaf nodes",
      "A tree that always uses every available attribute"
    ],
    correctAnswer: "The smallest tree that is consistent with the data",
    explanation: "Occam's Razor argues a short hypothesis consistent with the data is less likely to be a statistical fluke than a long, convoluted one."
  },
  {
    id: 25,
    question: "A decision tree can be interpreted as representing which logical structure over the attributes?",
    options: [
      "A single large conjunction of all attribute tests",
      "A disjunction of conjunctions — each root-to-leaf path is a conjunction of tests, and the tree is the disjunction (OR) of all such paths leading to the positive class",
      "A single negation of all attribute tests",
      "A linear combination (weighted sum) of the attribute values"
    ],
    correctAnswer: "A disjunction of conjunctions — each root-to-leaf path is a conjunction of tests, and the tree is the disjunction (OR) of all such paths leading to the positive class",
    explanation: "Each root-to-leaf path is a conjunction (AND) of attribute constraints, and the overall tree represents the disjunction (OR) of all paths ending at a target class."
  },
  {
    id: 26,
    question: "In the ID3 top-down induction algorithm, at each step the algorithm:",
    options: [
      "Randomly selects any attribute to split on",
      "Chooses the 'best' decision attribute for the node, assigns it, and creates a new descendant branch for each value of that attribute",
      "Always splits on the attribute that has the greatest number of possible values",
      "Stops only after every attribute has been used, regardless of node purity"
    ],
    correctAnswer: "Chooses the 'best' decision attribute for the node, assigns it, and creates a new descendant branch for each value of that attribute",
    explanation: "ID3 selects the attribute that maximizes information gain, creates a node for it, and branches out for each possible value of that attribute."
  },
  {
    id: 27,
    question: "According to the slides, under which condition(s) should ID3 stop growing a branch of the tree?\nI. There are no more input features left to split on\nII. All training examples at the node are classified the same (already pure)\nIII. There are too few examples remaining to make an informative split\nIV. Only once every single attribute in the dataset has been used, irrespective of purity",
    options: [
      "I, II, and III",
      "I and II only",
      "II and III only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and III",
    explanation: "The slides list three stopping criteria: when all examples have the same label (pure), when no features remain, or when too few examples remain. It does not blindly continue until all attributes are exhausted."
  },
  {
    id: 28,
    question: "What is the principled criterion used by ID3 to decide which attribute is 'best' to test at each node?",
    options: [
      "Euclidean distance between examples",
      "Information gain (based on reduction in entropy)",
      "Alphabetical order of the attribute names",
      "The number of missing values for the attribute"
    ],
    correctAnswer: "Information gain (based on reduction in entropy)",
    explanation: "ID3 measures the effectiveness of an attribute using Information Gain — the expected reduction in entropy resulting from splitting on that attribute."
  },
  {
    id: 29,
    question: "Entropy of a sample S, in terms of the proportion of positive (p+) and negative (p−) examples, is defined as:",
    options: [
      "Entropy(S) = p+ · p−",
      "Entropy(S) = −p+·log2(p+) − p−·log2(p−)",
      "Entropy(S) = p+ − p−",
      "Entropy(S) = (p+ + p−) / 2"
    ],
    correctAnswer: "Entropy(S) = −p+·log2(p+) − p−·log2(p−)",
    explanation: "Information theory defines entropy of a binary sample as: Entropy(S) = −p+·log2(p+) − p−·log2(p−)."
  },
  {
    id: 30,
    question: "A sample set S contains 12 positive and 4 negative examples (16 total). What is Entropy(S)? (round to 2 decimals)",
    options: [
      "0.81",
      "0.94",
      "0.65",
      "1.00"
    ],
    correctAnswer: "0.81",
    explanation: "p+ = 12/16 = 0.75, p− = 4/16 = 0.25. Entropy(S) = −0.75·log2(0.75) − 0.25·log2(0.25) = −0.75×(−0.415) − 0.25×(−2) = 0.311 + 0.500 = 0.811 ≈ 0.81."
  },
  {
    id: 31,
    question: "Reduced-Error Pruning is a post-pruning technique that works by:",
    options: [
      "Using the entire training set for both growing and validating the tree, with no separate validation data",
      "Partitioning the data into a 'grow' set and a 'validation' set, building a full tree on the grow set, and then repeatedly pruning the non-leaf node whose removal gives the greatest increase in validation accuracy, until accuracy no longer improves",
      "Never removing any node from the fully-grown tree under any circumstance",
      "Pruning based purely on alphabetical attribute names, without using any data"
    ],
    correctAnswer: "Partitioning the data into a 'grow' set and a 'validation' set, building a full tree on the grow set, and then repeatedly pruning the non-leaf node whose removal gives the greatest increase in validation accuracy, until accuracy no longer improves",
    explanation: "In reduced-error pruning, the dataset is split into training and validation sets. Subtrees are tentatively pruned to a majority leaf and kept pruned if accuracy on the validation set does not decrease."
  },

  // Section C: Information Gain & Gini Index (Q32–Q37)
  {
    id: 32,
    question: "Information Gain, Gain(S,A), for splitting sample S on attribute A is defined as:",
    options: [
      "Entropy(S) multiplied by the number of distinct values of A",
      "The expected reduction in entropy due to partitioning S on A: Gain(S,A) = Entropy(S) − Σv (|Sv|/|S|)·Entropy(Sv)",
      "The sum of the entropies of all the subsets Sv",
      "The maximum entropy among all the subsets Sv"
    ],
    correctAnswer: "The expected reduction in entropy due to partitioning S on A: Gain(S,A) = Entropy(S) − Σv (|Sv|/|S|)·Entropy(Sv)",
    explanation: "Information gain subtracts the weighted average entropy of the resulting subsets from the original entropy of sample S."
  },
  {
    id: 33,
    question: "For the PlayTennis-style dataset, Entropy(S) = 0.940 for S=[9+,5−]. Splitting on 'Humidity' gives: Humidity=High → 7 examples with entropy 0.985; Humidity=Normal → 7 examples with entropy 0.592. What is Gain(S, Humidity)? (round to 3 decimals)",
    options: [
      "0.151",
      "0.246",
      "0.048",
      "0.325"
    ],
    correctAnswer: "0.151",
    explanation: "Gain(S, Humidity) = 0.940 − (7/14)×0.985 − (7/14)×0.592 = 0.940 − 0.4925 − 0.296 = 0.940 − 0.7885 = 0.151."
  },
  {
    id: 34,
    question: "Using the sample S from Q30 (12+, 4−; Entropy(S)=0.81), suppose splitting on attribute A gives: Branch1 = [8+, 1−] (9 examples, Entropy ≈ 0.50) and Branch2 = [4+, 3−] (7 examples, Entropy ≈ 0.99). What is Gain(S, A)? (round to 2 decimals)",
    options: [
      "0.10",
      "0.25",
      "0.02",
      "0.38"
    ],
    correctAnswer: "0.10",
    explanation: "Gain(S, A) = Entropy(S) − (9/16)×0.50 − (7/16)×0.99 = 0.81 − 0.5625×0.50 − 0.4375×0.99 = 0.81 − 0.281 − 0.433 = 0.81 − 0.714 ≈ 0.10."
  },
  {
    id: 35,
    question: "The GINI Index of a node (a measure of node impurity) is defined as:",
    options: [
      "GINI(Node) = Σ [p(c)]² over all classes c",
      "GINI(Node) = 1 − Σ [p(c)]² over all classes c",
      "GINI(Node) = 1 + Σ [p(c)]²",
      "GINI(Node) = max over c of p(c)"
    ],
    correctAnswer: "GINI(Node) = 1 − Σ [p(c)]² over all classes c",
    explanation: "GINI impurity measures the probability of misclassifying a randomly selected element if labeled randomly according to the class distribution: GINI = 1 − Σ [p(c)]²."
  },
  {
    id: 36,
    question: "What is the Gini index of a node containing 90 positive and 60 negative examples (150 total)?",
    options: [
      "0.48",
      "0.52",
      "0.36",
      "0.64"
    ],
    correctAnswer: "0.48",
    explanation: "p+ = 90/150 = 0.6, p− = 60/150 = 0.4. GINI = 1 − [p+² + p−²] = 1 − [0.6² + 0.4²] = 1 − [0.36 + 0.16] = 1 − 0.52 = 0.48."
  },
  {
    id: 37,
    question: "A split on attribute A produces two children: Child1 has 70 examples (80% positive) and Child2 has 30 examples (30% positive). Using GINIsplit(A) = Σv (|Sv|/|S|)·GINI(Nv), what is GINIsplit(A)?",
    options: [
      "0.35",
      "0.42",
      "0.28",
      "0.50"
    ],
    correctAnswer: "0.35",
    explanation: "GINI(Child1) = 1 − [0.8² + 0.2²] = 1 − 0.68 = 0.32. GINI(Child2) = 1 − [0.3² + 0.7²] = 1 − 0.58 = 0.42. GINIsplit(A) = (70/100)×0.32 + (30/100)×0.42 = 0.224 + 0.126 = 0.35."
  },

  // Section D: Overfitting, Pruning & Model Complexity (Q38–Q45)
  {
    id: 38,
    question: "For a continuous-valued attribute, the 'binary split' approach used in decision trees works by:",
    options: [
      "Always using the mean of all the attribute's values as the split point, without testing alternatives",
      "Creating a new boolean attribute Ac = true if A ≤ c (false otherwise), after considering all possible thresholds c and choosing the best cut",
      "Always splitting the attribute's range into exactly 4 equal-width intervals",
      "Converting the continuous attribute to a categorical one using only its rank, ignoring the actual values"
    ],
    correctAnswer: "Creating a new boolean attribute Ac = true if A ≤ c (false otherwise), after considering all possible thresholds c and choosing the best cut",
    explanation: "Continuous attributes are handled by dynamically defining candidate threshold cuts c, evaluating candidate boolean tests A ≤ c, and selecting the threshold that maximizes information gain."
  },
  {
    id: 39,
    question: "According to the slides, finding the minimal decision tree that is consistent with a given set of training data is:",
    options: [
      "Solvable in polynomial time",
      "NP-hard",
      "Always solvable in O(n log n) time",
      "An undecidable problem"
    ],
    correctAnswer: "NP-hard",
    explanation: "Finding the globally minimal decision tree consistent with training data is known to be NP-hard, which necessitates heuristic greedy algorithms."
  },
  {
    id: 40,
    question: "Since finding the globally optimal decision tree is computationally hard, algorithms like ID3 instead perform:",
    options: [
      "An exhaustive, systematic search over every possible tree",
      "A greedy heuristic search — hill climbing without backtracking",
      "A purely random search with no evaluation criterion at all",
      "A brute-force search that is guaranteed to find the global optimum"
    ],
    correctAnswer: "A greedy heuristic search — hill climbing without backtracking",
    explanation: "ID3 executes a top-down greedy search (hill climbing), picking the locally best attribute at each node without ever backtracking."
  },
  {
    id: 41,
    question: "A hypothesis h is said to 'overfit' the training data if:",
    options: [
      "h has a larger error than another hypothesis h′ on both the training data and the test data",
      "There exists another hypothesis h′ such that h has smaller error than h′ on the training data, but h has larger error than h′ on the test data",
      "h and h′ always have identical training error",
      "Overfitting can only occur when the training set is extremely large"
    ],
    correctAnswer: "There exists another hypothesis h′ such that h has smaller error than h′ on the training data, but h has larger error than h′ on the test data",
    explanation: "A hypothesis h overfits when an alternative hypothesis h' exists that performs worse on the training set but achieves lower error on unseen test instances."
  },
  {
    id: 42,
    question: "Which of the following are cited in the slides as common causes of overfitting?\nI. Noise present in the training data\nII. The model/tree being based on insufficient (limited) training data\nIII. Using a separate validation set during training\nIV. Pruning the tree after it is fully built",
    options: [
      "I and II only",
      "I and III only",
      "II and IV only",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I and II only",
    explanation: "Noise in data and small/insufficient sample size are the primary causes of overfitting. Validation sets and pruning are remedies to combat overfitting."
  },
  {
    id: 43,
    question: "As model/tree complexity increases, what typically happens to the training error and the test (generalization) error?",
    options: [
      "Both training and test error keep decreasing indefinitely as complexity grows",
      "Training error keeps decreasing (often reaching 0), while test error decreases initially but then starts increasing beyond a certain complexity — this is overfitting",
      "Both training and test error increase together as complexity grows",
      "Training error increases while test error stays exactly constant"
    ],
    correctAnswer: "Training error keeps decreasing (often reaching 0), while test error decreases initially but then starts increasing beyond a certain complexity — this is overfitting",
    explanation: "Training error decreases monotonically with model complexity, but test error forms a characteristic U-curve: decreasing at first, then increasing as overfitting takes over."
  },
  {
    id: 44,
    question: "'Underfitting' is best described as the situation where:",
    options: [
      "The model is too simple, resulting in both high training error and high test error",
      "The model fits the training data perfectly but performs poorly on test data",
      "The model achieves zero error on both training and test data",
      "The model has far too many parameters relative to the amount of data"
    ],
    correctAnswer: "The model is too simple, resulting in both high training error and high test error",
    explanation: "Underfitting occurs when the hypothesis space is too restrictive or the model is too simple, leading to high error on both training and generalization data."
  },
  {
    id: 45,
    question: "Which of the following are valid Pre-pruning (early stopping) conditions for decision tree induction?\nI. Stop growing the tree if all instances at a node already belong to the same class\nII. Stop if the number of instances at a node falls below a user-specified threshold\nIII. Grow the tree fully first, then remove nodes afterward\nIV. Stop if expanding the current node does not improve an impurity measure such as information gain or Gini",
    options: [
      "I, II, and IV",
      "I, II, and III",
      "II, III, and IV",
      "All of I, II, III, and IV"
    ],
    correctAnswer: "I, II, and IV",
    explanation: "Pre-pruning halts expansion early using conditions I, II, and IV. Statement III describes post-pruning, not pre-pruning."
  }
];

// Week 4 Question Bank: Probability & Bayesian Learning (45 Questions)
// Sourced directly from Module 4 Practice Assessment (Prof. Sudeshna Sarkar, IIT Kharagpur)
const WEEK4_QUESTIONS = [
  // PART 1: PROBABILITY BASICS & RANDOM VARIABLES (Q1 – Q6)
  {
    id: 1,
    question: "An experiment consists of tossing a fair coin 3 times. What is the probability of the event C = 'at least two heads appear'?",
    options: [
      "1/4",
      "3/8",
      "1/2",
      "5/8"
    ],
    correctAnswer: "1/2",
    explanation: "The sample space has 2^3 = 8 equally likely outcomes: {HHH, HHT, HTH, HTT, THH, THT, TTH, TTT}. The event C ('at least two heads') contains {HHH, HHT, HTH, THH}, so |C| = 4. Therefore, P(C) = 4/8 = 1/2."
  },
  {
    id: 2,
    question: "Which of the following statements is strictly guaranteed by the fundamental axioms of probability for any events A and B?",
    options: [
      "If A ⊆ B, then P(A) ≥ P(B)",
      "P(A ∪ B) = P(A) + P(B) + P(A ∩ B)",
      "If A ⊆ B, then P(A) ≤ P(B)",
      "P(A) + P(A^c) > 1"
    ],
    correctAnswer: "If A ⊆ B, then P(A) ≤ P(B)",
    explanation: "By the monotonicity property of probability derived from Kolmogorov's axioms: if event A is a subset of event B (A ⊆ B), then P(A) ≤ P(B). Also, P(A ∪ B) = P(A) + P(B) - P(A ∩ B) and P(A) + P(A^c) = 1."
  },
  {
    id: 3,
    question: "A random variable X is defined formally as a function that:",
    options: [
      "Maps probability values to sample outcomes",
      "Maps outcomes from the sample space Ω into real scalar values",
      "Converts continuous density functions into integers",
      "Calculates the empirical frequency of trials"
    ],
    correctAnswer: "Maps outcomes from the sample space Ω into real scalar values",
    explanation: "Formally in probability theory, a random variable X is a measurable function X: Ω → ℝ that maps every elementary outcome ω in sample space Ω to a real number."
  },
  {
    id: 4,
    question: "For a discrete random variable X having probability mass function P(X = xi), which of the following is true for distinct outcomes xi ≠ xj?",
    options: [
      "P(X = xi ∩ X = xj) > 0",
      "P(X = xi ∩ X = xj) = 0",
      "P(X = xi ∪ X = xj) = P(X = xi) · P(X = xj)",
      "∑i P(X = xi) = ∞"
    ],
    correctAnswer: "P(X = xi ∩ X = xj) = 0",
    explanation: "In any single trial, the random variable X takes exactly one realization. Distinct values {X = xi} and {X = xj} are mutually disjoint events, meaning P(X = xi ∩ X = xj) = 0."
  },
  {
    id: 5,
    question: "If random variable X follows a Binomial distribution X ~ Bin(n, p), the probability mass function P(X = i) is:",
    options: [
      "(1/n) · p^i",
      "n! · p^i (1 - p)^(n-i)",
      "C(n, i) · p^i (1 - p)^(n-i)",
      "C(n, i) · p^(n-i) (1 - p)^n"
    ],
    correctAnswer: "C(n, i) · p^i (1 - p)^(n-i)",
    explanation: "The Binomial PMF for observing exactly i successes in n independent Bernoulli trials with success probability p is: P(X = i) = C(n, i) p^i (1 - p)^(n-i), where C(n, i) = n! / (i!(n - i)!)."
  },
  {
    id: 6,
    question: "By the Law of Total Probability, given discrete random variables X and Y, the marginal probability P(X = xi) is obtained by:",
    options: [
      "∑j P(X = xi | Y = yj) P(Y = yj)",
      "∏j P(X = xi, Y = yj)",
      "∑j P(Y = yj | X = xi)",
      "P(X = xi | Y = y1) / P(Y = y1)"
    ],
    correctAnswer: "∑j P(X = xi | Y = yj) P(Y = yj)",
    explanation: "The Law of Total Probability states that the marginal distribution is obtained by marginalizing over Y: P(X = xi) = ∑j P(X = xi, Y = yj) = ∑j P(X = xi | Y = yj) P(Y = yj)."
  },

  // PART 1: CONTINUOUS DISTRIBUTIONS (Q7 – Q12)
  {
    id: 7,
    question: "Two random variables X and Y are statistically independent if and only if:",
    options: [
      "P(X = x ∩ Y = y) = P(X = x) + P(Y = y)",
      "P(X = x | Y = y) = P(X = x) for all x, y",
      "P(X = x ∩ Y = y) = 0",
      "P(X = x | Y = y) = P(Y = y | X = x)"
    ],
    correctAnswer: "P(X = x | Y = y) = P(X = x) for all x, y",
    explanation: "Independence means that conditioning on Y provides no information about X: P(X = x | Y = y) = P(X = x), which is also equivalent to the product rule P(X = x, Y = y) = P(X = x) P(Y = y)."
  },
  {
    id: 8,
    question: "Which of the following conditions must hold for any valid probability density function f(x) of a continuous random variable X?",
    options: [
      "0 ≤ f(x) ≤ 1 for all x",
      "f(x) ≥ 0 for all x, and ∫_{-∞}^{∞} f(x) dx = 1",
      "f(x) = d/dx [P(X ≥ x)]",
      "f(x) cannot exceed 0.5 at any peak"
    ],
    correctAnswer: "f(x) ≥ 0 for all x, and ∫_{-∞}^{∞} f(x) dx = 1",
    explanation: "A continuous probability density function (PDF) must be non-negative everywhere (f(x) ≥ 0) and the total area under the curve must equal 1 (∫ f(x) dx = 1). Note that f(x) can exceed 1 locally because it represents density, not discrete probability."
  },
  {
    id: 9,
    question: "If F_X(x) is the Cumulative Distribution Function (CDF) of a continuous random variable X, how is the probability density function f(x) related to it?",
    options: [
      "f(x) = ∫_{-∞}^{x} F_X(t) dt",
      "f(x) = 1 - F_X(x)",
      "f(x) = d/dx [F_X(x)]",
      "f(x) = [F_X(x)]^2"
    ],
    correctAnswer: "f(x) = d/dx [F_X(x)]",
    explanation: "Since the CDF is F_X(x) = ∫_{-∞}^{x} f(t) dt, by the Fundamental Theorem of Calculus, the PDF is its first derivative: f(x) = d/dx [F_X(x)] = F'_X(x)."
  },
  {
    id: 10,
    question: "The probability density function of a 1D Normal distribution X ~ N(μ, σ^2) is given by:",
    options: [
      "(1 / (σ √(2π))) · exp{ -(x - μ) / (2σ) }",
      "(1 / (σ √(2π))) · exp{ -(x - μ)^2 / (2σ^2) }",
      "(1 / (2π σ^2)) · exp{ -(x - μ)^2 / σ^2 }",
      "√(2π) σ · exp{ -(x - μ)^2 / (2σ^2) }"
    ],
    correctAnswer: "(1 / (σ √(2π))) · exp{ -(x - μ)^2 / (2σ^2) }",
    explanation: "The standard univariate Normal (Gaussian) distribution density function with mean μ and variance σ^2 is f(x) = (1 / (σ √(2π))) · exp{ -(x - μ)^2 / (2σ^2) }."
  },
  {
    id: 11,
    question: "Given an unbiased sample variance estimator for N independent samples x1, ..., xN, what is the denominator used when estimating σ^2 from sample mean x̄?",
    options: [
      "N",
      "N - 1",
      "N + 1",
      "2N"
    ],
    correctAnswer: "N - 1",
    explanation: "Bessel's correction replaces N with N - 1 in the denominator: s^2 = 1/(N - 1) ∑ (xi - x̄)^2. This corrects the negative bias that arises because the sample mean x̄ is closer to the sample points than the true population mean μ."
  },
  {
    id: 12,
    question: "What is the covariance term in the exponent of a multivariate normal distribution of dimension d with covariance matrix Σ?",
    options: [
      "-(1/2) (x - μ)^T Σ (x - μ)",
      "-(1/2) (x - μ)^T Σ^-1 (x - μ)",
      "-(1/2) |Σ|^-1/2 (x - μ)",
      "-(d/2) (x - μ)^T Σ^-1 (x - μ)"
    ],
    correctAnswer: "-(1/2) (x - μ)^T Σ^-1 (x - μ)",
    explanation: "In the multivariate Gaussian density, the quadratic form in the exponent is -(1/2) (x - μ)^T Σ^-1 (x - μ), where Σ^-1 is the inverse covariance (precision) matrix."
  },

  // PART 2: BAYESIAN LEARNING & HYPOTHESES (Q13 – Q18)
  {
    id: 13,
    question: "In Bayes theorem, P(h | D) = [ P(D | h) P(h) ] / P(D), the term P(D | h) represents:",
    options: [
      "Posterior probability of hypothesis h",
      "Prior probability of hypothesis h",
      "Likelihood of the data D given hypothesis h",
      "Marginal evidence of the data D"
    ],
    correctAnswer: "Likelihood of the data D given hypothesis h",
    explanation: "P(D | h) denotes the likelihood of observing the training data D assuming hypothesis h holds true."
  },
  {
    id: 14,
    question: "The Maximum A Posteriori (MAP) hypothesis h_MAP is defined as:",
    options: [
      "arg max_{h ∈ H} P(D | h)",
      "arg max_{h ∈ H} P(h)",
      "arg max_{h ∈ H} [ P(D | h) P(h) ]",
      "arg max_{h ∈ H} [ P(D | h) / P(h) ]"
    ],
    correctAnswer: "arg max_{h ∈ H} [ P(D | h) P(h) ]",
    explanation: "h_MAP = arg max_{h ∈ H} P(h | D) = arg max_{h ∈ H} [ P(D | h) P(h) / P(D) ]. Since P(D) is independent of h, this simplifies to arg max_{h ∈ H} [ P(D | h) P(h) ]."
  },
  {
    id: 15,
    question: "Under what condition does the Maximum A Posteriori (MAP) hypothesis become strictly equivalent to the Maximum Likelihood (ML) hypothesis?",
    options: [
      "When the data likelihood follows a Gaussian distribution",
      "When every hypothesis in hypothesis space H is equally probable a priori",
      "When the number of training examples approaches zero",
      "When the feature attributes are conditionally independent"
    ],
    correctAnswer: "When every hypothesis in hypothesis space H is equally probable a priori",
    explanation: "If all hypotheses have uniform prior probability P(h) = constant, then arg max [P(D | h) P(h)] = arg max P(D | h) = h_ML."
  },
  {
    id: 16,
    question: "A cancer diagnostic test has true positive rate P(+ | cancer) = 0.98 and true negative rate P(- | ¬cancer) = 0.97. The disease prior is P(cancer) = 0.008. What is the unnormalized joint probability P(+ | cancer) P(cancer)?",
    options: [
      "0.02976",
      "0.00784",
      "0.98000",
      "0.03760"
    ],
    correctAnswer: "0.00784",
    explanation: "P(+ | cancer) P(cancer) = 0.98 × 0.008 = 0.00784."
  },
  {
    id: 17,
    question: "In the same cancer problem (from Q16), what is the unnormalized quantity P(+ | ¬cancer) P(¬cancer)? (Note: P(¬cancer) = 0.992 and false positive rate is 1 - 0.97 = 0.03)",
    options: [
      "0.02976",
      "0.00784",
      "0.00024",
      "0.96224"
    ],
    correctAnswer: "0.02976",
    explanation: "P(+ | ¬cancer) P(¬cancer) = (1 - 0.97) × 0.992 = 0.03 × 0.992 = 0.02976."
  },
  {
    id: 18,
    question: "Based on the calculations in Q16 and Q17, what is the MAP diagnosis for a patient whose test is positive?",
    options: [
      "Cancer, because the test accuracy is 98%",
      "¬Cancer, because P(+ , ¬cancer) = 0.02976 > P(+ , cancer) = 0.00784",
      "Undecidable without knowing the sample size",
      "Both are equally probable"
    ],
    correctAnswer: "¬Cancer, because P(+ , ¬cancer) = 0.02976 > P(+ , cancer) = 0.00784",
    explanation: "Comparing unnormalized posteriors: P(+ , ¬cancer) = 0.02976 is roughly 3.8 times larger than P(+ , cancer) = 0.00784. Thus, the MAP diagnosis is ¬cancer (the patient is more likely to be a false positive due to disease rarity)."
  },

  // PART 3: MAXIMUM LIKELIHOOD, LEAST SQUARES & BAYES OPTIMAL (Q19 – Q24)
  {
    id: 19,
    question: "When learning a continuous target function f(x) from noisy samples di = f(xi) + ei, the Maximum Likelihood hypothesis h_ML minimizes the sum of squared errors provided that noise ei is:",
    options: [
      "Uniformly distributed in [-1, 1]",
      "Independent and identically distributed Normal with zero mean and constant variance",
      "Dependent upon the target magnitude f(xi)",
      "Poisson distributed with rate λ = σ^2"
    ],
    correctAnswer: "Independent and identically distributed Normal with zero mean and constant variance",
    explanation: "Assuming noise terms ei are i.i.d. Gaussian N(0, σ^2), maximizing the log-likelihood of observations di is mathematically identical to minimizing the sum of squared errors."
  },
  {
    id: 20,
    question: "During the derivation of h_ML under i.i.d. Gaussian noise, maximizing the likelihood is equivalent to minimizing which objective function?",
    options: [
      "∑i=1^m |di - h(xi)|",
      "∑i=1^m (di - h(xi))^2",
      "∏i=1^m (di - h(xi))^2",
      "∑i=1^m ln(di - h(xi))"
    ],
    correctAnswer: "∑i=1^m (di - h(xi))^2",
    explanation: "The log-likelihood expression contains -1/(2σ^2) ∑ (di - h(xi))^2. Dropping constants and flipping the sign turns maximization into minimizing the sum of squared errors: ∑ (di - h(xi))^2."
  },
  {
    id: 21,
    question: "Why is the Bayes Optimal Classifier defined by arg max_{vj ∈ V} ∑_{hi ∈ H} P(vj | hi) P(hi | D) considered 'optimal'?",
    options: [
      "It trains faster than any other classification model",
      "No other classifier using the same hypothesis space and prior knowledge can outperform it on average",
      "It always selects a single hypothesis that has zero training error",
      "It eliminates the need for prior probabilities"
    ],
    correctAnswer: "No other classifier using the same hypothesis space and prior knowledge can outperform it on average",
    explanation: "By marginalizing over all hypotheses weighted by their posterior probabilities, the Bayes Optimal Classifier minimizes the expected prediction error over new instances."
  },
  {
    id: 22,
    question: "Consider three hypotheses: P(h1|D) = 0.4, P(h2|D) = 0.3, P(h3|D) = 0.3. For an instance x, predictions are h1(x) = +, h2(x) = -, h3(x) = -. What are the predictions of h_MAP and the Bayes Optimal Classifier respectively?",
    options: [
      "h_MAP: + ; Bayes Optimal: +",
      "h_MAP: - ; Bayes Optimal: -",
      "h_MAP: + ; Bayes Optimal: -",
      "h_MAP: - ; Bayes Optimal: +"
    ],
    correctAnswer: "h_MAP: + ; Bayes Optimal: -",
    explanation: "h_MAP is the hypothesis with the highest posterior: h1 (0.4), so h_MAP predicts '+'. But the Bayes Optimal Classifier sums posterior votes for each class: P(+) = 0.4, while P(-) = P(h2|D) + P(h3|D) = 0.3 + 0.3 = 0.6. Because 0.6 > 0.4, Bayes Optimal predicts '-'."
  },
  {
    id: 23,
    question: "What is the primary practical disadvantage of the Bayes Optimal Classifier that motivates the use of approximations like the Gibbs algorithm?",
    options: [
      "It suffers from severe underfitting on continuous data",
      "It is computationally prohibitive when the hypothesis space H is large",
      "It fails whenever the prior distribution is uniform",
      "Its predictions are non-deterministic"
    ],
    correctAnswer: "It is computationally prohibitive when the hypothesis space H is large",
    explanation: "Computing the Bayes Optimal classification requires evaluating every hypothesis in H and weighting by its posterior, which becomes computationally intractable when H is vast or infinite."
  },
  {
    id: 24,
    question: "Under the theorem proved by Haussler et al. (1994), what is the upper bound on the expected error of the Gibbs algorithm relative to the Bayes Optimal Classifier?",
    options: [
      "E[error_Gibbs] ≤ 0.5 · E[error_BayesOpt]",
      "E[error_Gibbs] ≤ E[error_BayesOpt]",
      "E[error_Gibbs] ≤ 2 · E[error_BayesOpt]",
      "E[error_Gibbs] ≤ e^2 · E[error_BayesOpt]"
    ],
    correctAnswer: "E[error_Gibbs] ≤ 2 · E[error_BayesOpt]",
    explanation: "Haussler et al. (1994) showed that sampling a single hypothesis according to its posterior distribution (Gibbs algorithm) yields an expected error at most twice that of the Bayes Optimal classifier: E[error_Gibbs] ≤ 2 · E[error_BayesOpt]."
  },

  // PART 4: NAÏVE BAYES CLASSIFIER (Q25 – Q30)
  {
    id: 25,
    question: "What is the foundational assumption made by the Naïve Bayes classifier that simplifies the computation of P(X1, ..., Xn | Y)?",
    options: [
      "Features Xi are mutually independent of the class Y",
      "Features Xi are conditionally independent of each other given the class label Y",
      "All attributes follow a standard Gaussian distribution",
      "The prior probabilities of all classes are identical"
    ],
    correctAnswer: "Features Xi are conditionally independent of each other given the class label Y",
    explanation: "The Naïve Bayes assumption states that all feature attributes are conditionally independent given the class label: P(X1, ..., Xn | Y) = ∏i=1^n P(Xi | Y)."
  },
  {
    id: 26,
    question: "If a discrete attribute Xi has J distinct values and class Y has K categories, how many independent conditional parameters P(Xi = x | Y = y) must be estimated for that feature across all classes?",
    options: [
      "K · (J - 1)",
      "K^J",
      "J · (K - 1)",
      "J · K"
    ],
    correctAnswer: "K · (J - 1)",
    explanation: "For each class y, the probabilities ∑_{x} P(Xi = x | Y = y) must sum to 1, leaving J - 1 free (independent) parameters. Across K classes, the total number of independent parameters is K · (J - 1)."
  },
  {
    id: 27,
    question: "In the 14-day PlayTennis dataset (9 Yes, 5 No), the attribute Outlook is 'Overcast' in 4 'Yes' days and 0 'No' days. What is the MLE estimate of P(Outlook = Overcast | Play = No)?",
    options: [
      "4/14",
      "0/5 = 0",
      "1/5",
      "4/9"
    ],
    correctAnswer: "0/5 = 0",
    explanation: "The Maximum Likelihood Estimate is the empirical count ratio: Count(Outlook=Overcast ∧ Play=No) / Count(Play=No) = 0 / 5 = 0."
  },
  {
    id: 28,
    question: "When using the Maximum Likelihood Estimate (MLE), if an attribute value never appears with a particular class in training, what severe issue occurs during test-time classification?",
    options: [
      "The prior probability of that class becomes negative",
      "The entire class-conditional posterior product evaluates to zero, wiping out all other feature evidence",
      "The algorithm enters an infinite recursion loop",
      "Variance becomes infinite"
    ],
    correctAnswer: "The entire class-conditional posterior product evaluates to zero, wiping out all other feature evidence",
    explanation: "Because Naïve Bayes computes the posterior via a product ∏ P(Xi | Y), a single zero probability forces the entire posterior product to zero, regardless of how strongly all other features support that class."
  },
  {
    id: 29,
    question: "To prevent zero probability probabilities in discrete Naïve Bayes, smoothing is applied: θ̂ijk = [ #D{Xi = xij ∧ Y = yk} + l ] / [ #D{Y = yk} + l · M ]. What does M represent?",
    options: [
      "Total number of training instances in D",
      "The number of distinct classes in Y",
      "The number of possible distinct values that attribute Xi can take",
      "The regularization strength parameter"
    ],
    correctAnswer: "The number of possible distinct values that attribute Xi can take",
    explanation: "M is the arity (number of distinct discrete values) that attribute Xi can assume, ensuring that summing the smoothed probabilities over all j distinct values equals 1."
  },
  {
    id: 30,
    question: "In Gaussian Naïve Bayes for continuous attributes, the class-conditional probability P(Xi = x | Y = yk) is modeled as:",
    options: [
      "A multi-dimensional uniform distribution",
      "A normal distribution with class-specific mean μik and variance σik^2",
      "A discrete Bernoulli probability mass function",
      "An exponential decay kernel with parameter λ = μ / σ"
    ],
    correctAnswer: "A normal distribution with class-specific mean μik and variance σik^2",
    explanation: "Gaussian Naïve Bayes models each continuous feature conditioned on class yk as a 1D Normal distribution: P(Xi = x | Y = yk) = (1 / (σik √(2π))) exp{ -(x - μik)^2 / (2σik^2) }."
  },

  // PART 5: GAUSSIAN NAÏVE BAYES & BAYESIAN NETWORKS (Q31 – Q36)
  {
    id: 31,
    question: "In Gaussian Naïve Bayes, if we constrain the variance to be identical across all classes for feature Xi (i.e., σik = σi), what type of decision boundary is formed between classes?",
    options: [
      "Quadratic decision boundary",
      "Linear decision boundary",
      "Piecewise step function",
      "Circular contour only"
    ],
    correctAnswer: "Linear decision boundary",
    explanation: "When variances are assumed equal across classes (homoscedasticity), the quadratic terms x^2 / (2σ^2) in the log-odds ratio cancel out, producing a linear decision boundary."
  },
  {
    id: 32,
    question: "Even when the conditional independence assumption is violated in real data, Naïve Bayes often performs remarkably well in classification because:",
    options: [
      "Accurate probability calibration is not strictly required to obtain the correct arg max class label",
      "Correlated features automatically cancel each other out mathematically",
      "The sample variance converges to zero",
      "It calculates full high-order joint covariance matrices"
    ],
    correctAnswer: "Accurate probability calibration is not strictly required to obtain the correct arg max class label",
    explanation: "Classification decisions depend solely on the arg max ranking, not on exact probability calibration. Even if independence violations skew probabilities towards 0 or 1, the winning class often remains unchanged."
  },
  {
    id: 33,
    question: "What graph structure constitutes the backbone of a Bayesian Belief Network?",
    options: [
      "Undirected cyclic graph",
      "Directed Acyclic Graph (DAG)",
      "Fully connected bipartite graph",
      "Maximum spanning tree"
    ],
    correctAnswer: "Directed Acyclic Graph (DAG)",
    explanation: "A Bayesian Belief Network is formally composed of a Directed Acyclic Graph (DAG) whose nodes represent variables and directed edges represent direct dependencies."
  },
  {
    id: 34,
    question: "In a Bayesian Network, what does the absence of a directed arc between two variables directly imply?",
    options: [
      "The variables have zero covariance under all circumstances",
      "The two variables are deterministic functions of each other",
      "A conditional independence assertion between those variables",
      "One of the variables must be a continuous Gaussian variable"
    ],
    correctAnswer: "A conditional independence assertion between those variables",
    explanation: "The absence of edges encodes conditional independence assertions in the graph, reducing the number of joint distribution parameters."
  },
  {
    id: 35,
    question: "According to the local Markov property in Bayesian Belief Networks, each node X is conditionally independent of:",
    options: [
      "Its immediate children given its parents",
      "Its non-descendants, given its immediate parents",
      "All other nodes in the entire network regardless of conditioning",
      "Its parents, given its children"
    ],
    correctAnswer: "Its non-descendants, given its immediate parents",
    explanation: "The local Markov property dictates that each variable X is conditionally independent of its non-descendants, given its immediate parents in the DAG."
  },
  {
    id: 36,
    question: "For a set of variables X = {X1, ..., XN} structured in a Bayesian Network, how does the full joint probability distribution factorize?",
    options: [
      "P(X1, ..., XN) = ∏i=1^N P(Xi)",
      "P(X1, ..., XN) = ∏i=1^N P(Xi | parents(Xi))",
      "P(X1, ..., XN) = ∑i=1^N P(Xi | children(Xi))",
      "P(X1, ..., XN) = ∏i=1^N P(parents(Xi) | Xi)"
    ],
    correctAnswer: "P(X1, ..., XN) = ∏i=1^N P(Xi | parents(Xi))",
    explanation: "By the Bayesian network factorization rule (chain rule for BNs), the joint probability is the product of conditional probabilities of each variable given its graph parents: P(X1, ..., XN) = ∏i=1^N P(Xi | parents(Xi))."
  },

  // PART 6: NETWORK TOPOLOGIES, HMMS & INFERENCE (Q37 – Q42)
  {
    id: 37,
    question: "In a common-cause structure where node A points to both B and C (B ← A → C), which condition holds?",
    options: [
      "B and C are marginally independent: P(B, C) = P(B)P(C)",
      "B and C are conditionally independent given A: P(B, C | A) = P(B | A) P(C | A)",
      "Knowing B gives no information about A",
      "A is independent of itself given B"
    ],
    correctAnswer: "B and C are conditionally independent given A: P(B, C | A) = P(B | A) P(C | A)",
    explanation: "In a diverging common cause structure (B ← A → C), B and C are generally dependent, but conditioning on the common cause A d-separates them, making them conditionally independent."
  },
  {
    id: 38,
    question: "Consider a v-structure (independent causes) where A → C ← B. If the common child C is observed, the phenomenon where confirming A reduces the probability of B is known as:",
    options: [
      "Markov blanket saturation",
      "\"Explaining away\"",
      "Laplace smoothing",
      "Gibbs sampling bias"
    ],
    correctAnswer: "\"Explaining away\"",
    explanation: "In a collider/v-structure (A → C ← B), causes A and B are marginally independent. Observing effect C makes them dependent: learning that A occurred explains away the evidence for C, reducing the likelihood that B occurred."
  },
  {
    id: 39,
    question: "In a first-order Markov chain sequence A → B → C, the joint probability simplifies to:",
    options: [
      "P(A) P(B | A) P(C | B)",
      "P(A) P(B) P(C)",
      "P(C | A, B) P(A)",
      "P(A | B) P(B | C) P(C)"
    ],
    correctAnswer: "P(A) P(B | A) P(C | B)",
    explanation: "In a linear Markov chain A → B → C, state C depends only on its immediate predecessor B (P(C | A, B) = P(C | B)), giving P(A, B, C) = P(A) P(B | A) P(C | B)."
  },
  {
    id: 40,
    question: "What are the two core conditional independence assumptions underpinning a standard Hidden Markov Model (HMM) with hidden states St and observations Yt?",
    options: [
      "All observations are independent of hidden states; hidden states are uniform",
      "Hidden state sequence is Markovian; observation Yt depends only on current state St",
      "Observations follow a Poisson process; transition probabilities are symmetric",
      "The chain is undirected and cycles are permitted"
    ],
    correctAnswer: "Hidden state sequence is Markovian; observation Yt depends only on current state St",
    explanation: "A standard HMM assumes: (1) the hidden state transition is first-order Markovian: P(St | St-1, ... S1) = P(St | St-1), and (2) observation emissions depend strictly on the current state: P(Yt | S1..St, Y1..Yt-1) = P(Yt | St)."
  },
  {
    id: 41,
    question: "What is the computational complexity of exact probabilistic inference in an arbitrary, general Bayesian Belief Network?",
    options: [
      "Strictly linear in the number of edges O(|E|)",
      "Polynomial time O(N^3)",
      "NP-hard",
      "Constant time O(1)"
    ],
    correctAnswer: "NP-hard",
    explanation: "Gregory Cooper (1990) proved that exact inference in general Bayesian networks is NP-hard, which necessitates approximate inference techniques like Gibbs sampling or belief propagation for polytrees."
  },
  {
    id: 42,
    question: "When learning a Bayesian Network whose graph structure is known in advance but some variables are hidden/unobservable, which algorithmic method is typically employed?",
    options: [
      "Simple empirical count ratio (direct MLE)",
      "Gradient Ascent / Expectation-Maximization (EM)",
      "Exhaustive breadth-first search",
      "Linear perceptron learning rule"
    ],
    correctAnswer: "Gradient Ascent / Expectation-Maximization (EM)",
    explanation: "When latent (hidden) variables exist in a known graph structure, closed-form MLE is unavailable, so the Expectation-Maximization (EM) algorithm or gradient ascent on the log-likelihood is used."
  },

  // PART 7: SYNTHESIS QUESTIONS (Q43 – Q45)
  {
    id: 43,
    question: "When the graph structure of a Bayesian Network is completely unknown in advance, the learning process requires:",
    options: [
      "Exact matrix inversion of the full covariance table",
      "Heuristic search or constraint-based techniques over the space of DAG structures",
      "Assuming all features are pairwise independent",
      "Applying the Gibbs classifier directly"
    ],
    correctAnswer: "Heuristic search or constraint-based techniques over the space of DAG structures",
    explanation: "Learning graph topology from data is an NP-hard problem. It requires heuristic score-based search (e.g., hill-climbing over candidate DAGs) or constraint-based conditional independence tests (e.g., PC algorithm)."
  },
  {
    id: 44,
    question: "How does a standard Naïve Bayes classifier relate structurally to a Bayesian Belief Network?",
    options: [
      "It is a special BN where the target class node is the single parent of all attribute nodes",
      "It is a Bayesian Network with undirected edges only",
      "It is equivalent to a fully connected DAG where every node points to every other node",
      "It cannot be represented as a Bayesian Network"
    ],
    correctAnswer: "It is a special BN where the target class node is the single parent of all attribute nodes",
    explanation: "Naïve Bayes is structurally a Bayesian network where the class node Y is the sole parent directing edges to each observed feature Xi (Y → Xi), with no edges among the features."
  },
  {
    id: 45,
    question: "If event A and event B are mutually disjoint with P(A) > 0 and P(B) > 0, can they also be statistically independent?",
    options: [
      "Yes, mutual exclusivity implies independence",
      "No, because P(A ∩ B) = 0, whereas independence requires P(A ∩ B) = P(A)P(B) > 0",
      "Yes, provided their sample space is infinite",
      "Only if both events have probability 0.5"
    ],
    correctAnswer: "No, because P(A ∩ B) = 0, whereas independence requires P(A ∩ B) = P(A)P(B) > 0",
    explanation: "Mutually disjoint events have P(A ∩ B) = 0. Independence requires P(A ∩ B) = P(A)P(B). If P(A) > 0 and P(B) > 0, their product is strictly positive, making independence impossible. In fact, disjoint events are maximally dependent: knowing A occurred guarantees B did not."
  }
];

// Metadata & Configuration for all available weeks
const WEEKS_DATA = {
  1: {
    id: 1,
    title: "Week 1",
    subheading: "Week 1 • Foundations & Evaluation",
    name: "Foundations & Evaluation",
    heroBadge: "46 Questions Available",
    heroTitle: "Prepare Your Practice Session",
    heroDesc: "Test your understanding on Mitchell's definition, Supervised/Unsupervised paradigms, Inductive Bias, Precision/Recall/F1, Overfitting, and K-Fold Cross Validation.",
    topics: ["Mitchell's Definition", "Supervised / Unsupervised", "Inductive Bias", "Precision, Recall & F1", "Confusion Matrix", "K-Fold Cross Validation"],
    totalQuestions: WEEK1_QUESTIONS.length,
    questions: WEEK1_QUESTIONS
  },
  2: {
    id: 2,
    title: "Week 2",
    subheading: "Week 2 • Linear Regression & Decision Trees",
    name: "Linear Regression & Decision Trees",
    heroBadge: "45 Questions Available",
    heroTitle: "Prepare Your Practice Session",
    heroDesc: "Test your understanding on Linear Regression, Least Squares (LMS), Gradient Descent (Batch & SGD), Decision Trees (ID3), Information Gain, Gini Index, and Pruning.",
    topics: ["Linear Regression & LMS", "Gradient Descent / SGD", "Decision Trees & ID3", "Entropy & Information Gain", "GINI Index & Splitting", "Overfitting & Pruning"],
    totalQuestions: WEEK2_QUESTIONS.length,
    questions: WEEK2_QUESTIONS
  },
  4: {
    id: 4,
    title: "Week 4",
    subheading: "Week 4 • Probability & Bayesian Learning",
    name: "Probability & Bayesian Learning",
    heroBadge: "45 Questions Available",
    heroTitle: "Prepare Your Practice Session",
    heroDesc: "Test your understanding on Probability Axioms, MAP vs ML Hypotheses, Bayes Optimal Classifier, Naïve Bayes, Gaussian NB, and Bayesian Belief Networks.",
    topics: ["Probability Axioms & Distributions", "MAP vs ML Hypotheses", "Bayes Optimal & Gibbs", "Naïve Bayes Classifier", "Gaussian NB & Smoothing", "Bayesian Networks & HMMs"],
    totalQuestions: WEEK4_QUESTIONS.length,
    questions: WEEK4_QUESTIONS
  }
};

// Global reference for backwards compatibility
let CURRENT_WEEK = 1;
let QUESTIONS_BANK = WEEK1_QUESTIONS;

